// Code generated by ent, DO NOT EDIT.

package pointsledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldUserID, v))
}

// Delta applies equality check predicate on the "delta" field. It's identical to DeltaEQ.
func Delta(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldDelta, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldReason, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldNote, v))
}

// PaymentID applies equality check predicate on the "payment_id" field. It's identical to PaymentIDEQ.
func PaymentID(v int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldPaymentID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotNull(FieldUserID))
}

// DeltaEQ applies the EQ predicate on the "delta" field.
func DeltaEQ(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldDelta, v))
}

// DeltaNEQ applies the NEQ predicate on the "delta" field.
func DeltaNEQ(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldDelta, v))
}

// DeltaIn applies the In predicate on the "delta" field.
func DeltaIn(vs ...int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldDelta, vs...))
}

// DeltaNotIn applies the NotIn predicate on the "delta" field.
func DeltaNotIn(vs ...int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldDelta, vs...))
}

// DeltaGT applies the GT predicate on the "delta" field.
func DeltaGT(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGT(FieldDelta, v))
}

// DeltaGTE applies the GTE predicate on the "delta" field.
func DeltaGTE(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGTE(FieldDelta, v))
}

// DeltaLT applies the LT predicate on the "delta" field.
func DeltaLT(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLT(FieldDelta, v))
}

// DeltaLTE applies the LTE predicate on the "delta" field.
func DeltaLTE(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLTE(FieldDelta, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v int64) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLTE(FieldBalanceAfter, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldContainsFold(FieldReason, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldContainsFold(FieldNote, v))
}

// PaymentIDEQ applies the EQ predicate on the "payment_id" field.
func PaymentIDEQ(v int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldEQ(FieldPaymentID, v))
}

// PaymentIDNEQ applies the NEQ predicate on the "payment_id" field.
func PaymentIDNEQ(v int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNEQ(FieldPaymentID, v))
}

// PaymentIDIn applies the In predicate on the "payment_id" field.
func PaymentIDIn(vs ...int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIn(FieldPaymentID, vs...))
}

// PaymentIDNotIn applies the NotIn predicate on the "payment_id" field.
func PaymentIDNotIn(vs ...int) predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotIn(FieldPaymentID, vs...))
}

// PaymentIDIsNil applies the IsNil predicate on the "payment_id" field.
func PaymentIDIsNil() predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldIsNull(FieldPaymentID))
}

// PaymentIDNotNil applies the NotNil predicate on the "payment_id" field.
func PaymentIDNotNil() predicate.PointsLedger {
	return predicate.PointsLedger(sql.FieldNotNull(FieldPaymentID))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.PointsLedger {
	return predicate.PointsLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.PointsLedger {
	return predicate.PointsLedger(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPayment applies the HasEdge predicate on the "payment" edge.
func HasPayment() predicate.PointsLedger {
	return predicate.PointsLedger(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PaymentTable, PaymentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentWith applies the HasEdge predicate on the "payment" edge with a given conditions (other predicates).
func HasPaymentWith(preds ...predicate.Payment) predicate.PointsLedger {
	return predicate.PointsLedger(func(s *sql.Selector) {
		step := newPaymentStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PointsLedger) predicate.PointsLedger {
	return predicate.PointsLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PointsLedger) predicate.PointsLedger {
	return predicate.PointsLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PointsLedger) predicate.PointsLedger {
	return predicate.PointsLedger(sql.NotPredicates(p))
}
