// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/abusereport"
)

// AbuseReportCreate is the builder for creating a AbuseReport entity.
type AbuseReportCreate struct {
	config
	mutation *AbuseReportMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (arc *AbuseReportCreate) SetCreatedAt(t time.Time) *AbuseReportCreate {
	arc.mutation.SetCreatedAt(t)
	return arc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableCreatedAt(t *time.Time) *AbuseReportCreate {
	if t != nil {
		arc.SetCreatedAt(*t)
	}
	return arc
}

// SetUpdatedAt sets the "updated_at" field.
func (arc *AbuseReportCreate) SetUpdatedAt(t time.Time) *AbuseReportCreate {
	arc.mutation.SetUpdatedAt(t)
	return arc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableUpdatedAt(t *time.Time) *AbuseReportCreate {
	if t != nil {
		arc.SetUpdatedAt(*t)
	}
	return arc
}

// SetDeletedAt sets the "deleted_at" field.
func (arc *AbuseReportCreate) SetDeletedAt(t time.Time) *AbuseReportCreate {
	arc.mutation.SetDeletedAt(t)
	return arc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableDeletedAt(t *time.Time) *AbuseReportCreate {
	if t != nil {
		arc.SetDeletedAt(*t)
	}
	return arc
}

// SetShareID sets the "share_id" field.
func (arc *AbuseReportCreate) SetShareID(i int) *AbuseReportCreate {
	arc.mutation.SetShareID(i)
	return arc
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableShareID(i *int) *AbuseReportCreate {
	if i != nil {
		arc.SetShareID(*i)
	}
	return arc
}

// SetShareURL sets the "share_url" field.
func (arc *AbuseReportCreate) SetShareURL(s string) *AbuseReportCreate {
	arc.mutation.SetShareURL(s)
	return arc
}

// SetNillableShareURL sets the "share_url" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableShareURL(s *string) *AbuseReportCreate {
	if s != nil {
		arc.SetShareURL(*s)
	}
	return arc
}

// SetReporterEmail sets the "reporter_email" field.
func (arc *AbuseReportCreate) SetReporterEmail(s string) *AbuseReportCreate {
	arc.mutation.SetReporterEmail(s)
	return arc
}

// SetNillableReporterEmail sets the "reporter_email" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableReporterEmail(s *string) *AbuseReportCreate {
	if s != nil {
		arc.SetReporterEmail(*s)
	}
	return arc
}

// SetIP sets the "ip" field.
func (arc *AbuseReportCreate) SetIP(s string) *AbuseReportCreate {
	arc.mutation.SetIP(s)
	return arc
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableIP(s *string) *AbuseReportCreate {
	if s != nil {
		arc.SetIP(*s)
	}
	return arc
}

// SetReason sets the "reason" field.
func (arc *AbuseReportCreate) SetReason(s string) *AbuseReportCreate {
	arc.mutation.SetReason(s)
	return arc
}

// SetStatus sets the "status" field.
func (arc *AbuseReportCreate) SetStatus(s string) *AbuseReportCreate {
	arc.mutation.SetStatus(s)
	return arc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableStatus(s *string) *AbuseReportCreate {
	if s != nil {
		arc.SetStatus(*s)
	}
	return arc
}

// SetNote sets the "note" field.
func (arc *AbuseReportCreate) SetNote(s string) *AbuseReportCreate {
	arc.mutation.SetNote(s)
	return arc
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableNote(s *string) *AbuseReportCreate {
	if s != nil {
		arc.SetNote(*s)
	}
	return arc
}

// Mutation returns the AbuseReportMutation object of the builder.
func (arc *AbuseReportCreate) Mutation() *AbuseReportMutation {
	return arc.mutation
}

// Save creates the AbuseReport in the database.
func (arc *AbuseReportCreate) Save(ctx context.Context) (*AbuseReport, error) {
	if err := arc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, arc.sqlSave, arc.mutation, arc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (arc *AbuseReportCreate) SaveX(ctx context.Context) *AbuseReport {
	v, err := arc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arc *AbuseReportCreate) Exec(ctx context.Context) error {
	_, err := arc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arc *AbuseReportCreate) ExecX(ctx context.Context) {
	if err := arc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (arc *AbuseReportCreate) defaults() error {
	if _, ok := arc.mutation.CreatedAt(); !ok {
		if abusereport.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized abusereport.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := abusereport.DefaultCreatedAt()
		arc.mutation.SetCreatedAt(v)
	}
	if _, ok := arc.mutation.UpdatedAt(); !ok {
		if abusereport.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized abusereport.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := abusereport.DefaultUpdatedAt()
		arc.mutation.SetUpdatedAt(v)
	}
	if _, ok := arc.mutation.Status(); !ok {
		v := abusereport.DefaultStatus
		arc.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (arc *AbuseReportCreate) check() error {
	if _, ok := arc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AbuseReport.created_at"`)}
	}
	if _, ok := arc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AbuseReport.updated_at"`)}
	}
	if v, ok := arc.mutation.ShareURL(); ok {
		if err := abusereport.ShareURLValidator(v); err != nil {
			return &ValidationError{Name: "share_url", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.share_url": %w`, err)}
		}
	}
	if v, ok := arc.mutation.ReporterEmail(); ok {
		if err := abusereport.ReporterEmailValidator(v); err != nil {
			return &ValidationError{Name: "reporter_email", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.reporter_email": %w`, err)}
		}
	}
	if v, ok := arc.mutation.IP(); ok {
		if err := abusereport.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.ip": %w`, err)}
		}
	}
	if _, ok := arc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "AbuseReport.reason"`)}
	}
	if _, ok := arc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AbuseReport.status"`)}
	}
	if v, ok := arc.mutation.Status(); ok {
		if err := abusereport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.status": %w`, err)}
		}
	}
	return nil
}

func (arc *AbuseReportCreate) sqlSave(ctx context.Context) (*AbuseReport, error) {
	if err := arc.check(); err != nil {
		return nil, err
	}
	_node, _spec := arc.createSpec()
	if err := sqlgraph.CreateNode(ctx, arc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	arc.mutation.id = &_node.ID
	arc.mutation.done = true
	return _node, nil
}

func (arc *AbuseReportCreate) createSpec() (*AbuseReport, *sqlgraph.CreateSpec) {
	var (
		_node = &AbuseReport{config: arc.config}
		_spec = sqlgraph.NewCreateSpec(abusereport.Table, sqlgraph.NewFieldSpec(abusereport.FieldID, field.TypeInt))
	)

	if id, ok := arc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = arc.conflict
	if value, ok := arc.mutation.CreatedAt(); ok {
		_spec.SetField(abusereport.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := arc.mutation.UpdatedAt(); ok {
		_spec.SetField(abusereport.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := arc.mutation.DeletedAt(); ok {
		_spec.SetField(abusereport.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := arc.mutation.ShareID(); ok {
		_spec.SetField(abusereport.FieldShareID, field.TypeInt, value)
		_node.ShareID = value
	}
	if value, ok := arc.mutation.ShareURL(); ok {
		_spec.SetField(abusereport.FieldShareURL, field.TypeString, value)
		_node.ShareURL = value
	}
	if value, ok := arc.mutation.ReporterEmail(); ok {
		_spec.SetField(abusereport.FieldReporterEmail, field.TypeString, value)
		_node.ReporterEmail = value
	}
	if value, ok := arc.mutation.IP(); ok {
		_spec.SetField(abusereport.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := arc.mutation.Reason(); ok {
		_spec.SetField(abusereport.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := arc.mutation.Status(); ok {
		_spec.SetField(abusereport.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := arc.mutation.Note(); ok {
		_spec.SetField(abusereport.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AbuseReport.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AbuseReportUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (arc *AbuseReportCreate) OnConflict(opts ...sql.ConflictOption) *AbuseReportUpsertOne {
	arc.conflict = opts
	return &AbuseReportUpsertOne{
		create: arc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (arc *AbuseReportCreate) OnConflictColumns(columns ...string) *AbuseReportUpsertOne {
	arc.conflict = append(arc.conflict, sql.ConflictColumns(columns...))
	return &AbuseReportUpsertOne{
		create: arc,
	}
}

type (
	// AbuseReportUpsertOne is the builder for "upsert"-ing
	//  one AbuseReport node.
	AbuseReportUpsertOne struct {
		create *AbuseReportCreate
	}

	// AbuseReportUpsert is the "OnConflict" setter.
	AbuseReportUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AbuseReportUpsert) SetUpdatedAt(v time.Time) *AbuseReportUpsert {
	u.Set(abusereport.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateUpdatedAt() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AbuseReportUpsert) SetDeletedAt(v time.Time) *AbuseReportUpsert {
	u.Set(abusereport.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateDeletedAt() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AbuseReportUpsert) ClearDeletedAt() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldDeletedAt)
	return u
}

// SetShareID sets the "share_id" field.
func (u *AbuseReportUpsert) SetShareID(v int) *AbuseReportUpsert {
	u.Set(abusereport.FieldShareID, v)
	return u
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateShareID() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldShareID)
	return u
}

// AddShareID adds v to the "share_id" field.
func (u *AbuseReportUpsert) AddShareID(v int) *AbuseReportUpsert {
	u.Add(abusereport.FieldShareID, v)
	return u
}

// ClearShareID clears the value of the "share_id" field.
func (u *AbuseReportUpsert) ClearShareID() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldShareID)
	return u
}

// SetShareURL sets the "share_url" field.
func (u *AbuseReportUpsert) SetShareURL(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldShareURL, v)
	return u
}

// UpdateShareURL sets the "share_url" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateShareURL() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldShareURL)
	return u
}

// ClearShareURL clears the value of the "share_url" field.
func (u *AbuseReportUpsert) ClearShareURL() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldShareURL)
	return u
}

// SetReporterEmail sets the "reporter_email" field.
func (u *AbuseReportUpsert) SetReporterEmail(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldReporterEmail, v)
	return u
}

// UpdateReporterEmail sets the "reporter_email" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateReporterEmail() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldReporterEmail)
	return u
}

// ClearReporterEmail clears the value of the "reporter_email" field.
func (u *AbuseReportUpsert) ClearReporterEmail() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldReporterEmail)
	return u
}

// SetIP sets the "ip" field.
func (u *AbuseReportUpsert) SetIP(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateIP() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *AbuseReportUpsert) ClearIP() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldIP)
	return u
}

// SetReason sets the "reason" field.
func (u *AbuseReportUpsert) SetReason(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateReason() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldReason)
	return u
}

// SetStatus sets the "status" field.
func (u *AbuseReportUpsert) SetStatus(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateStatus() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldStatus)
	return u
}

// SetNote sets the "note" field.
func (u *AbuseReportUpsert) SetNote(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateNote() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *AbuseReportUpsert) ClearNote() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldNote)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AbuseReportUpsertOne) UpdateNewValues() *AbuseReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(abusereport.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AbuseReportUpsertOne) Ignore() *AbuseReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AbuseReportUpsertOne) DoNothing() *AbuseReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AbuseReportCreate.OnConflict
// documentation for more info.
func (u *AbuseReportUpsertOne) Update(set func(*AbuseReportUpsert)) *AbuseReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AbuseReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AbuseReportUpsertOne) SetUpdatedAt(v time.Time) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateUpdatedAt() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AbuseReportUpsertOne) SetDeletedAt(v time.Time) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateDeletedAt() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AbuseReportUpsertOne) ClearDeletedAt() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearDeletedAt()
	})
}

// SetShareID sets the "share_id" field.
func (u *AbuseReportUpsertOne) SetShareID(v int) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetShareID(v)
	})
}

// AddShareID adds v to the "share_id" field.
func (u *AbuseReportUpsertOne) AddShareID(v int) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.AddShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateShareID() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateShareID()
	})
}

// ClearShareID clears the value of the "share_id" field.
func (u *AbuseReportUpsertOne) ClearShareID() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearShareID()
	})
}

// SetShareURL sets the "share_url" field.
func (u *AbuseReportUpsertOne) SetShareURL(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetShareURL(v)
	})
}

// UpdateShareURL sets the "share_url" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateShareURL() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateShareURL()
	})
}

// ClearShareURL clears the value of the "share_url" field.
func (u *AbuseReportUpsertOne) ClearShareURL() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearShareURL()
	})
}

// SetReporterEmail sets the "reporter_email" field.
func (u *AbuseReportUpsertOne) SetReporterEmail(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReporterEmail(v)
	})
}

// UpdateReporterEmail sets the "reporter_email" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateReporterEmail() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReporterEmail()
	})
}

// ClearReporterEmail clears the value of the "reporter_email" field.
func (u *AbuseReportUpsertOne) ClearReporterEmail() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearReporterEmail()
	})
}

// SetIP sets the "ip" field.
func (u *AbuseReportUpsertOne) SetIP(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateIP() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *AbuseReportUpsertOne) ClearIP() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearIP()
	})
}

// SetReason sets the "reason" field.
func (u *AbuseReportUpsertOne) SetReason(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateReason() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReason()
	})
}

// SetStatus sets the "status" field.
func (u *AbuseReportUpsertOne) SetStatus(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateStatus() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateStatus()
	})
}

// SetNote sets the "note" field.
func (u *AbuseReportUpsertOne) SetNote(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateNote() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *AbuseReportUpsertOne) ClearNote() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *AbuseReportUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AbuseReportCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AbuseReportUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AbuseReportUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AbuseReportUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *AbuseReportCreate) SetRawID(t int) *AbuseReportCreate {
	m.mutation.SetRawID(t)
	return m
}

// AbuseReportCreateBulk is the builder for creating many AbuseReport entities in bulk.
type AbuseReportCreateBulk struct {
	config
	err      error
	builders []*AbuseReportCreate
	conflict []sql.ConflictOption
}

// Save creates the AbuseReport entities in the database.
func (arcb *AbuseReportCreateBulk) Save(ctx context.Context) ([]*AbuseReport, error) {
	if arcb.err != nil {
		return nil, arcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(arcb.builders))
	nodes := make([]*AbuseReport, len(arcb.builders))
	mutators := make([]Mutator, len(arcb.builders))
	for i := range arcb.builders {
		func(i int, root context.Context) {
			builder := arcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AbuseReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, arcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = arcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, arcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, arcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (arcb *AbuseReportCreateBulk) SaveX(ctx context.Context) []*AbuseReport {
	v, err := arcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arcb *AbuseReportCreateBulk) Exec(ctx context.Context) error {
	_, err := arcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arcb *AbuseReportCreateBulk) ExecX(ctx context.Context) {
	if err := arcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AbuseReport.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AbuseReportUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (arcb *AbuseReportCreateBulk) OnConflict(opts ...sql.ConflictOption) *AbuseReportUpsertBulk {
	arcb.conflict = opts
	return &AbuseReportUpsertBulk{
		create: arcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (arcb *AbuseReportCreateBulk) OnConflictColumns(columns ...string) *AbuseReportUpsertBulk {
	arcb.conflict = append(arcb.conflict, sql.ConflictColumns(columns...))
	return &AbuseReportUpsertBulk{
		create: arcb,
	}
}

// AbuseReportUpsertBulk is the builder for "upsert"-ing
// a bulk of AbuseReport nodes.
type AbuseReportUpsertBulk struct {
	create *AbuseReportCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AbuseReportUpsertBulk) UpdateNewValues() *AbuseReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(abusereport.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AbuseReportUpsertBulk) Ignore() *AbuseReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AbuseReportUpsertBulk) DoNothing() *AbuseReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AbuseReportCreateBulk.OnConflict
// documentation for more info.
func (u *AbuseReportUpsertBulk) Update(set func(*AbuseReportUpsert)) *AbuseReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AbuseReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AbuseReportUpsertBulk) SetUpdatedAt(v time.Time) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateUpdatedAt() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AbuseReportUpsertBulk) SetDeletedAt(v time.Time) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateDeletedAt() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AbuseReportUpsertBulk) ClearDeletedAt() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearDeletedAt()
	})
}

// SetShareID sets the "share_id" field.
func (u *AbuseReportUpsertBulk) SetShareID(v int) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetShareID(v)
	})
}

// AddShareID adds v to the "share_id" field.
func (u *AbuseReportUpsertBulk) AddShareID(v int) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.AddShareID(v)
	})
}

// UpdateShareID sets the "share_id" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateShareID() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateShareID()
	})
}

// ClearShareID clears the value of the "share_id" field.
func (u *AbuseReportUpsertBulk) ClearShareID() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearShareID()
	})
}

// SetShareURL sets the "share_url" field.
func (u *AbuseReportUpsertBulk) SetShareURL(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetShareURL(v)
	})
}

// UpdateShareURL sets the "share_url" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateShareURL() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateShareURL()
	})
}

// ClearShareURL clears the value of the "share_url" field.
func (u *AbuseReportUpsertBulk) ClearShareURL() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearShareURL()
	})
}

// SetReporterEmail sets the "reporter_email" field.
func (u *AbuseReportUpsertBulk) SetReporterEmail(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReporterEmail(v)
	})
}

// UpdateReporterEmail sets the "reporter_email" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateReporterEmail() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReporterEmail()
	})
}

// ClearReporterEmail clears the value of the "reporter_email" field.
func (u *AbuseReportUpsertBulk) ClearReporterEmail() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearReporterEmail()
	})
}

// SetIP sets the "ip" field.
func (u *AbuseReportUpsertBulk) SetIP(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateIP() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *AbuseReportUpsertBulk) ClearIP() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearIP()
	})
}

// SetReason sets the "reason" field.
func (u *AbuseReportUpsertBulk) SetReason(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateReason() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReason()
	})
}

// SetStatus sets the "status" field.
func (u *AbuseReportUpsertBulk) SetStatus(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateStatus() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateStatus()
	})
}

// SetNote sets the "note" field.
func (u *AbuseReportUpsertBulk) SetNote(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateNote() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *AbuseReportUpsertBulk) ClearNote() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearNote()
	})
}

// Exec executes the query.
func (u *AbuseReportUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AbuseReportCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AbuseReportCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AbuseReportUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
