// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/abusereport"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// AbuseReportUpdate is the builder for updating AbuseReport entities.
type AbuseReportUpdate struct {
	config
	hooks    []Hook
	mutation *AbuseReportMutation
}

// Where appends a list predicates to the AbuseReportUpdate builder.
func (aru *AbuseReportUpdate) Where(ps ...predicate.AbuseReport) *AbuseReportUpdate {
	aru.mutation.Where(ps...)
	return aru
}

// SetUpdatedAt sets the "updated_at" field.
func (aru *AbuseReportUpdate) SetUpdatedAt(t time.Time) *AbuseReportUpdate {
	aru.mutation.SetUpdatedAt(t)
	return aru
}

// SetDeletedAt sets the "deleted_at" field.
func (aru *AbuseReportUpdate) SetDeletedAt(t time.Time) *AbuseReportUpdate {
	aru.mutation.SetDeletedAt(t)
	return aru
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (aru *AbuseReportUpdate) SetNillableDeletedAt(t *time.Time) *AbuseReportUpdate {
	if t != nil {
		aru.SetDeletedAt(*t)
	}
	return aru
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (aru *AbuseReportUpdate) ClearDeletedAt() *AbuseReportUpdate {
	aru.mutation.ClearDeletedAt()
	return aru
}

// SetShareID sets the "share_id" field.
func (aru *AbuseReportUpdate) SetShareID(i int) *AbuseReportUpdate {
	aru.mutation.ResetShareID()
	aru.mutation.SetShareID(i)
	return aru
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (aru *AbuseReportUpdate) SetNillableShareID(i *int) *AbuseReportUpdate {
	if i != nil {
		aru.SetShareID(*i)
	}
	return aru
}

// AddShareID adds i to the "share_id" field.
func (aru *AbuseReportUpdate) AddShareID(i int) *AbuseReportUpdate {
	aru.mutation.AddShareID(i)
	return aru
}

// ClearShareID clears the value of the "share_id" field.
func (aru *AbuseReportUpdate) ClearShareID() *AbuseReportUpdate {
	aru.mutation.ClearShareID()
	return aru
}

// SetShareURL sets the "share_url" field.
func (aru *AbuseReportUpdate) SetShareURL(s string) *AbuseReportUpdate {
	aru.mutation.SetShareURL(s)
	return aru
}

// SetNillableShareURL sets the "share_url" field if the given value is not nil.
func (aru *AbuseReportUpdate) SetNillableShareURL(s *string) *AbuseReportUpdate {
	if s != nil {
		aru.SetShareURL(*s)
	}
	return aru
}

// ClearShareURL clears the value of the "share_url" field.
func (aru *AbuseReportUpdate) ClearShareURL() *AbuseReportUpdate {
	aru.mutation.ClearShareURL()
	return aru
}

// SetReporterEmail sets the "reporter_email" field.
func (aru *AbuseReportUpdate) SetReporterEmail(s string) *AbuseReportUpdate {
	aru.mutation.SetReporterEmail(s)
	return aru
}

// SetNillableReporterEmail sets the "reporter_email" field if the given value is not nil.
func (aru *AbuseReportUpdate) SetNillableReporterEmail(s *string) *AbuseReportUpdate {
	if s != nil {
		aru.SetReporterEmail(*s)
	}
	return aru
}

// ClearReporterEmail clears the value of the "reporter_email" field.
func (aru *AbuseReportUpdate) ClearReporterEmail() *AbuseReportUpdate {
	aru.mutation.ClearReporterEmail()
	return aru
}

// SetIP sets the "ip" field.
func (aru *AbuseReportUpdate) SetIP(s string) *AbuseReportUpdate {
	aru.mutation.SetIP(s)
	return aru
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (aru *AbuseReportUpdate) SetNillableIP(s *string) *AbuseReportUpdate {
	if s != nil {
		aru.SetIP(*s)
	}
	return aru
}

// ClearIP clears the value of the "ip" field.
func (aru *AbuseReportUpdate) ClearIP() *AbuseReportUpdate {
	aru.mutation.ClearIP()
	return aru
}

// SetReason sets the "reason" field.
func (aru *AbuseReportUpdate) SetReason(s string) *AbuseReportUpdate {
	aru.mutation.SetReason(s)
	return aru
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (aru *AbuseReportUpdate) SetNillableReason(s *string) *AbuseReportUpdate {
	if s != nil {
		aru.SetReason(*s)
	}
	return aru
}

// SetStatus sets the "status" field.
func (aru *AbuseReportUpdate) SetStatus(s string) *AbuseReportUpdate {
	aru.mutation.SetStatus(s)
	return aru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (aru *AbuseReportUpdate) SetNillableStatus(s *string) *AbuseReportUpdate {
	if s != nil {
		aru.SetStatus(*s)
	}
	return aru
}

// SetNote sets the "note" field.
func (aru *AbuseReportUpdate) SetNote(s string) *AbuseReportUpdate {
	aru.mutation.SetNote(s)
	return aru
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (aru *AbuseReportUpdate) SetNillableNote(s *string) *AbuseReportUpdate {
	if s != nil {
		aru.SetNote(*s)
	}
	return aru
}

// ClearNote clears the value of the "note" field.
func (aru *AbuseReportUpdate) ClearNote() *AbuseReportUpdate {
	aru.mutation.ClearNote()
	return aru
}

// Mutation returns the AbuseReportMutation object of the builder.
func (aru *AbuseReportUpdate) Mutation() *AbuseReportMutation {
	return aru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aru *AbuseReportUpdate) Save(ctx context.Context) (int, error) {
	if err := aru.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, aru.sqlSave, aru.mutation, aru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aru *AbuseReportUpdate) SaveX(ctx context.Context) int {
	affected, err := aru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aru *AbuseReportUpdate) Exec(ctx context.Context) error {
	_, err := aru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aru *AbuseReportUpdate) ExecX(ctx context.Context) {
	if err := aru.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aru *AbuseReportUpdate) defaults() error {
	if _, ok := aru.mutation.UpdatedAt(); !ok {
		if abusereport.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized abusereport.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := abusereport.UpdateDefaultUpdatedAt()
		aru.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (aru *AbuseReportUpdate) check() error {
	if v, ok := aru.mutation.ShareURL(); ok {
		if err := abusereport.ShareURLValidator(v); err != nil {
			return &ValidationError{Name: "share_url", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.share_url": %w`, err)}
		}
	}
	if v, ok := aru.mutation.ReporterEmail(); ok {
		if err := abusereport.ReporterEmailValidator(v); err != nil {
			return &ValidationError{Name: "reporter_email", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.reporter_email": %w`, err)}
		}
	}
	if v, ok := aru.mutation.IP(); ok {
		if err := abusereport.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.ip": %w`, err)}
		}
	}
	if v, ok := aru.mutation.Status(); ok {
		if err := abusereport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.status": %w`, err)}
		}
	}
	return nil
}

func (aru *AbuseReportUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(abusereport.Table, abusereport.Columns, sqlgraph.NewFieldSpec(abusereport.FieldID, field.TypeInt))
	if ps := aru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aru.mutation.UpdatedAt(); ok {
		_spec.SetField(abusereport.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aru.mutation.DeletedAt(); ok {
		_spec.SetField(abusereport.FieldDeletedAt, field.TypeTime, value)
	}
	if aru.mutation.DeletedAtCleared() {
		_spec.ClearField(abusereport.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := aru.mutation.ShareID(); ok {
		_spec.SetField(abusereport.FieldShareID, field.TypeInt, value)
	}
	if value, ok := aru.mutation.AddedShareID(); ok {
		_spec.AddField(abusereport.FieldShareID, field.TypeInt, value)
	}
	if aru.mutation.ShareIDCleared() {
		_spec.ClearField(abusereport.FieldShareID, field.TypeInt)
	}
	if value, ok := aru.mutation.ShareURL(); ok {
		_spec.SetField(abusereport.FieldShareURL, field.TypeString, value)
	}
	if aru.mutation.ShareURLCleared() {
		_spec.ClearField(abusereport.FieldShareURL, field.TypeString)
	}
	if value, ok := aru.mutation.ReporterEmail(); ok {
		_spec.SetField(abusereport.FieldReporterEmail, field.TypeString, value)
	}
	if aru.mutation.ReporterEmailCleared() {
		_spec.ClearField(abusereport.FieldReporterEmail, field.TypeString)
	}
	if value, ok := aru.mutation.IP(); ok {
		_spec.SetField(abusereport.FieldIP, field.TypeString, value)
	}
	if aru.mutation.IPCleared() {
		_spec.ClearField(abusereport.FieldIP, field.TypeString)
	}
	if value, ok := aru.mutation.Reason(); ok {
		_spec.SetField(abusereport.FieldReason, field.TypeString, value)
	}
	if value, ok := aru.mutation.Status(); ok {
		_spec.SetField(abusereport.FieldStatus, field.TypeString, value)
	}
	if value, ok := aru.mutation.Note(); ok {
		_spec.SetField(abusereport.FieldNote, field.TypeString, value)
	}
	if aru.mutation.NoteCleared() {
		_spec.ClearField(abusereport.FieldNote, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{abusereport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aru.mutation.done = true
	return n, nil
}

// AbuseReportUpdateOne is the builder for updating a single AbuseReport entity.
type AbuseReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AbuseReportMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (aruo *AbuseReportUpdateOne) SetUpdatedAt(t time.Time) *AbuseReportUpdateOne {
	aruo.mutation.SetUpdatedAt(t)
	return aruo
}

// SetDeletedAt sets the "deleted_at" field.
func (aruo *AbuseReportUpdateOne) SetDeletedAt(t time.Time) *AbuseReportUpdateOne {
	aruo.mutation.SetDeletedAt(t)
	return aruo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (aruo *AbuseReportUpdateOne) SetNillableDeletedAt(t *time.Time) *AbuseReportUpdateOne {
	if t != nil {
		aruo.SetDeletedAt(*t)
	}
	return aruo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (aruo *AbuseReportUpdateOne) ClearDeletedAt() *AbuseReportUpdateOne {
	aruo.mutation.ClearDeletedAt()
	return aruo
}

// SetShareID sets the "share_id" field.
func (aruo *AbuseReportUpdateOne) SetShareID(i int) *AbuseReportUpdateOne {
	aruo.mutation.ResetShareID()
	aruo.mutation.SetShareID(i)
	return aruo
}

// SetNillableShareID sets the "share_id" field if the given value is not nil.
func (aruo *AbuseReportUpdateOne) SetNillableShareID(i *int) *AbuseReportUpdateOne {
	if i != nil {
		aruo.SetShareID(*i)
	}
	return aruo
}

// AddShareID adds i to the "share_id" field.
func (aruo *AbuseReportUpdateOne) AddShareID(i int) *AbuseReportUpdateOne {
	aruo.mutation.AddShareID(i)
	return aruo
}

// ClearShareID clears the value of the "share_id" field.
func (aruo *AbuseReportUpdateOne) ClearShareID() *AbuseReportUpdateOne {
	aruo.mutation.ClearShareID()
	return aruo
}

// SetShareURL sets the "share_url" field.
func (aruo *AbuseReportUpdateOne) SetShareURL(s string) *AbuseReportUpdateOne {
	aruo.mutation.SetShareURL(s)
	return aruo
}

// SetNillableShareURL sets the "share_url" field if the given value is not nil.
func (aruo *AbuseReportUpdateOne) SetNillableShareURL(s *string) *AbuseReportUpdateOne {
	if s != nil {
		aruo.SetShareURL(*s)
	}
	return aruo
}

// ClearShareURL clears the value of the "share_url" field.
func (aruo *AbuseReportUpdateOne) ClearShareURL() *AbuseReportUpdateOne {
	aruo.mutation.ClearShareURL()
	return aruo
}

// SetReporterEmail sets the "reporter_email" field.
func (aruo *AbuseReportUpdateOne) SetReporterEmail(s string) *AbuseReportUpdateOne {
	aruo.mutation.SetReporterEmail(s)
	return aruo
}

// SetNillableReporterEmail sets the "reporter_email" field if the given value is not nil.
func (aruo *AbuseReportUpdateOne) SetNillableReporterEmail(s *string) *AbuseReportUpdateOne {
	if s != nil {
		aruo.SetReporterEmail(*s)
	}
	return aruo
}

// ClearReporterEmail clears the value of the "reporter_email" field.
func (aruo *AbuseReportUpdateOne) ClearReporterEmail() *AbuseReportUpdateOne {
	aruo.mutation.ClearReporterEmail()
	return aruo
}

// SetIP sets the "ip" field.
func (aruo *AbuseReportUpdateOne) SetIP(s string) *AbuseReportUpdateOne {
	aruo.mutation.SetIP(s)
	return aruo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (aruo *AbuseReportUpdateOne) SetNillableIP(s *string) *AbuseReportUpdateOne {
	if s != nil {
		aruo.SetIP(*s)
	}
	return aruo
}

// ClearIP clears the value of the "ip" field.
func (aruo *AbuseReportUpdateOne) ClearIP() *AbuseReportUpdateOne {
	aruo.mutation.ClearIP()
	return aruo
}

// SetReason sets the "reason" field.
func (aruo *AbuseReportUpdateOne) SetReason(s string) *AbuseReportUpdateOne {
	aruo.mutation.SetReason(s)
	return aruo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (aruo *AbuseReportUpdateOne) SetNillableReason(s *string) *AbuseReportUpdateOne {
	if s != nil {
		aruo.SetReason(*s)
	}
	return aruo
}

// SetStatus sets the "status" field.
func (aruo *AbuseReportUpdateOne) SetStatus(s string) *AbuseReportUpdateOne {
	aruo.mutation.SetStatus(s)
	return aruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (aruo *AbuseReportUpdateOne) SetNillableStatus(s *string) *AbuseReportUpdateOne {
	if s != nil {
		aruo.SetStatus(*s)
	}
	return aruo
}

// SetNote sets the "note" field.
func (aruo *AbuseReportUpdateOne) SetNote(s string) *AbuseReportUpdateOne {
	aruo.mutation.SetNote(s)
	return aruo
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (aruo *AbuseReportUpdateOne) SetNillableNote(s *string) *AbuseReportUpdateOne {
	if s != nil {
		aruo.SetNote(*s)
	}
	return aruo
}

// ClearNote clears the value of the "note" field.
func (aruo *AbuseReportUpdateOne) ClearNote() *AbuseReportUpdateOne {
	aruo.mutation.ClearNote()
	return aruo
}

// Mutation returns the AbuseReportMutation object of the builder.
func (aruo *AbuseReportUpdateOne) Mutation() *AbuseReportMutation {
	return aruo.mutation
}

// Where appends a list predicates to the AbuseReportUpdate builder.
func (aruo *AbuseReportUpdateOne) Where(ps ...predicate.AbuseReport) *AbuseReportUpdateOne {
	aruo.mutation.Where(ps...)
	return aruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aruo *AbuseReportUpdateOne) Select(field string, fields ...string) *AbuseReportUpdateOne {
	aruo.fields = append([]string{field}, fields...)
	return aruo
}

// Save executes the query and returns the updated AbuseReport entity.
func (aruo *AbuseReportUpdateOne) Save(ctx context.Context) (*AbuseReport, error) {
	if err := aruo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, aruo.sqlSave, aruo.mutation, aruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aruo *AbuseReportUpdateOne) SaveX(ctx context.Context) *AbuseReport {
	node, err := aruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aruo *AbuseReportUpdateOne) Exec(ctx context.Context) error {
	_, err := aruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aruo *AbuseReportUpdateOne) ExecX(ctx context.Context) {
	if err := aruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aruo *AbuseReportUpdateOne) defaults() error {
	if _, ok := aruo.mutation.UpdatedAt(); !ok {
		if abusereport.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized abusereport.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := abusereport.UpdateDefaultUpdatedAt()
		aruo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (aruo *AbuseReportUpdateOne) check() error {
	if v, ok := aruo.mutation.ShareURL(); ok {
		if err := abusereport.ShareURLValidator(v); err != nil {
			return &ValidationError{Name: "share_url", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.share_url": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.ReporterEmail(); ok {
		if err := abusereport.ReporterEmailValidator(v); err != nil {
			return &ValidationError{Name: "reporter_email", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.reporter_email": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.IP(); ok {
		if err := abusereport.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.ip": %w`, err)}
		}
	}
	if v, ok := aruo.mutation.Status(); ok {
		if err := abusereport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.status": %w`, err)}
		}
	}
	return nil
}

func (aruo *AbuseReportUpdateOne) sqlSave(ctx context.Context) (_node *AbuseReport, err error) {
	if err := aruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(abusereport.Table, abusereport.Columns, sqlgraph.NewFieldSpec(abusereport.FieldID, field.TypeInt))
	id, ok := aruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AbuseReport.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, abusereport.FieldID)
		for _, f := range fields {
			if !abusereport.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != abusereport.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aruo.mutation.UpdatedAt(); ok {
		_spec.SetField(abusereport.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aruo.mutation.DeletedAt(); ok {
		_spec.SetField(abusereport.FieldDeletedAt, field.TypeTime, value)
	}
	if aruo.mutation.DeletedAtCleared() {
		_spec.ClearField(abusereport.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := aruo.mutation.ShareID(); ok {
		_spec.SetField(abusereport.FieldShareID, field.TypeInt, value)
	}
	if value, ok := aruo.mutation.AddedShareID(); ok {
		_spec.AddField(abusereport.FieldShareID, field.TypeInt, value)
	}
	if aruo.mutation.ShareIDCleared() {
		_spec.ClearField(abusereport.FieldShareID, field.TypeInt)
	}
	if value, ok := aruo.mutation.ShareURL(); ok {
		_spec.SetField(abusereport.FieldShareURL, field.TypeString, value)
	}
	if aruo.mutation.ShareURLCleared() {
		_spec.ClearField(abusereport.FieldShareURL, field.TypeString)
	}
	if value, ok := aruo.mutation.ReporterEmail(); ok {
		_spec.SetField(abusereport.FieldReporterEmail, field.TypeString, value)
	}
	if aruo.mutation.ReporterEmailCleared() {
		_spec.ClearField(abusereport.FieldReporterEmail, field.TypeString)
	}
	if value, ok := aruo.mutation.IP(); ok {
		_spec.SetField(abusereport.FieldIP, field.TypeString, value)
	}
	if aruo.mutation.IPCleared() {
		_spec.ClearField(abusereport.FieldIP, field.TypeString)
	}
	if value, ok := aruo.mutation.Reason(); ok {
		_spec.SetField(abusereport.FieldReason, field.TypeString, value)
	}
	if value, ok := aruo.mutation.Status(); ok {
		_spec.SetField(abusereport.FieldStatus, field.TypeString, value)
	}
	if value, ok := aruo.mutation.Note(); ok {
		_spec.SetField(abusereport.FieldNote, field.TypeString, value)
	}
	if aruo.mutation.NoteCleared() {
		_spec.ClearField(abusereport.FieldNote, field.TypeString)
	}
	_node = &AbuseReport{config: aruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{abusereport.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aruo.mutation.done = true
	return _node, nil
}
