// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/abusereport"
)

// AbuseReport is the model entity for the AbuseReport schema.
type AbuseReport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// ShareID holds the value of the "share_id" field.
	ShareID int `json:"share_id,omitempty"`
	// ShareURL holds the value of the "share_url" field.
	ShareURL string `json:"share_url,omitempty"`
	// ReporterEmail holds the value of the "reporter_email" field.
	ReporterEmail string `json:"reporter_email,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Note holds the value of the "note" field.
	Note         string `json:"note,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AbuseReport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case abusereport.FieldID, abusereport.FieldShareID:
			values[i] = new(sql.NullInt64)
		case abusereport.FieldShareURL, abusereport.FieldReporterEmail, abusereport.FieldIP, abusereport.FieldReason, abusereport.FieldStatus, abusereport.FieldNote:
			values[i] = new(sql.NullString)
		case abusereport.FieldCreatedAt, abusereport.FieldUpdatedAt, abusereport.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AbuseReport fields.
func (ar *AbuseReport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case abusereport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ar.ID = int(value.Int64)
		case abusereport.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ar.CreatedAt = value.Time
			}
		case abusereport.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ar.UpdatedAt = value.Time
			}
		case abusereport.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ar.DeletedAt = new(time.Time)
				*ar.DeletedAt = value.Time
			}
		case abusereport.FieldShareID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field share_id", values[i])
			} else if value.Valid {
				ar.ShareID = int(value.Int64)
			}
		case abusereport.FieldShareURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field share_url", values[i])
			} else if value.Valid {
				ar.ShareURL = value.String
			}
		case abusereport.FieldReporterEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_email", values[i])
			} else if value.Valid {
				ar.ReporterEmail = value.String
			}
		case abusereport.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				ar.IP = value.String
			}
		case abusereport.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				ar.Reason = value.String
			}
		case abusereport.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ar.Status = value.String
			}
		case abusereport.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				ar.Note = value.String
			}
		default:
			ar.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AbuseReport.
// This includes values selected through modifiers, order, etc.
func (ar *AbuseReport) Value(name string) (ent.Value, error) {
	return ar.selectValues.Get(name)
}

// Update returns a builder for updating this AbuseReport.
// Note that you need to call AbuseReport.Unwrap() before calling this method if this AbuseReport
// was returned from a transaction, and the transaction was committed or rolled back.
func (ar *AbuseReport) Update() *AbuseReportUpdateOne {
	return NewAbuseReportClient(ar.config).UpdateOne(ar)
}

// Unwrap unwraps the AbuseReport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ar *AbuseReport) Unwrap() *AbuseReport {
	_tx, ok := ar.config.driver.(*txDriver)
	if !ok {
		panic("ent: AbuseReport is not a transactional entity")
	}
	ar.config.driver = _tx.drv
	return ar
}

// String implements the fmt.Stringer.
func (ar *AbuseReport) String() string {
	var builder strings.Builder
	builder.WriteString("AbuseReport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ar.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ar.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ar.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ar.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("share_id=")
	builder.WriteString(fmt.Sprintf("%v", ar.ShareID))
	builder.WriteString(", ")
	builder.WriteString("share_url=")
	builder.WriteString(ar.ShareURL)
	builder.WriteString(", ")
	builder.WriteString("reporter_email=")
	builder.WriteString(ar.ReporterEmail)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(ar.IP)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(ar.Reason)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(ar.Status)
	builder.WriteString(", ")
	builder.WriteString("note=")
	builder.WriteString(ar.Note)
	builder.WriteByte(')')
	return builder.String()
}

// AbuseReports is a parsable slice of AbuseReport.
type AbuseReports []*AbuseReport
