// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/giftcode"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// GiftCodeCreate is the builder for creating a GiftCode entity.
type GiftCodeCreate struct {
	config
	mutation *GiftCodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (gcc *GiftCodeCreate) SetCreatedAt(t time.Time) *GiftCodeCreate {
	gcc.mutation.SetCreatedAt(t)
	return gcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableCreatedAt(t *time.Time) *GiftCodeCreate {
	if t != nil {
		gcc.SetCreatedAt(*t)
	}
	return gcc
}

// SetUpdatedAt sets the "updated_at" field.
func (gcc *GiftCodeCreate) SetUpdatedAt(t time.Time) *GiftCodeCreate {
	gcc.mutation.SetUpdatedAt(t)
	return gcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableUpdatedAt(t *time.Time) *GiftCodeCreate {
	if t != nil {
		gcc.SetUpdatedAt(*t)
	}
	return gcc
}

// SetDeletedAt sets the "deleted_at" field.
func (gcc *GiftCodeCreate) SetDeletedAt(t time.Time) *GiftCodeCreate {
	gcc.mutation.SetDeletedAt(t)
	return gcc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableDeletedAt(t *time.Time) *GiftCodeCreate {
	if t != nil {
		gcc.SetDeletedAt(*t)
	}
	return gcc
}

// SetCode sets the "code" field.
func (gcc *GiftCodeCreate) SetCode(s string) *GiftCodeCreate {
	gcc.mutation.SetCode(s)
	return gcc
}

// SetProductType sets the "product_type" field.
func (gcc *GiftCodeCreate) SetProductType(s string) *GiftCodeCreate {
	gcc.mutation.SetProductType(s)
	return gcc
}

// SetNum sets the "num" field.
func (gcc *GiftCodeCreate) SetNum(i int64) *GiftCodeCreate {
	gcc.mutation.SetNum(i)
	return gcc
}

// SetName sets the "name" field.
func (gcc *GiftCodeCreate) SetName(s string) *GiftCodeCreate {
	gcc.mutation.SetName(s)
	return gcc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableName(s *string) *GiftCodeCreate {
	if s != nil {
		gcc.SetName(*s)
	}
	return gcc
}

// SetUsed sets the "used" field.
func (gcc *GiftCodeCreate) SetUsed(b bool) *GiftCodeCreate {
	gcc.mutation.SetUsed(b)
	return gcc
}

// SetNillableUsed sets the "used" field if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableUsed(b *bool) *GiftCodeCreate {
	if b != nil {
		gcc.SetUsed(*b)
	}
	return gcc
}

// SetUsedBy sets the "used_by" field.
func (gcc *GiftCodeCreate) SetUsedBy(i int) *GiftCodeCreate {
	gcc.mutation.SetUsedBy(i)
	return gcc
}

// SetNillableUsedBy sets the "used_by" field if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableUsedBy(i *int) *GiftCodeCreate {
	if i != nil {
		gcc.SetUsedBy(*i)
	}
	return gcc
}

// SetUsedByEmail sets the "used_by_email" field.
func (gcc *GiftCodeCreate) SetUsedByEmail(s string) *GiftCodeCreate {
	gcc.mutation.SetUsedByEmail(s)
	return gcc
}

// SetNillableUsedByEmail sets the "used_by_email" field if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableUsedByEmail(s *string) *GiftCodeCreate {
	if s != nil {
		gcc.SetUsedByEmail(*s)
	}
	return gcc
}

// SetCreatedByEmail sets the "created_by_email" field.
func (gcc *GiftCodeCreate) SetCreatedByEmail(s string) *GiftCodeCreate {
	gcc.mutation.SetCreatedByEmail(s)
	return gcc
}

// SetNillableCreatedByEmail sets the "created_by_email" field if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableCreatedByEmail(s *string) *GiftCodeCreate {
	if s != nil {
		gcc.SetCreatedByEmail(*s)
	}
	return gcc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (gcc *GiftCodeCreate) SetUserID(id int) *GiftCodeCreate {
	gcc.mutation.SetUserID(id)
	return gcc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (gcc *GiftCodeCreate) SetNillableUserID(id *int) *GiftCodeCreate {
	if id != nil {
		gcc = gcc.SetUserID(*id)
	}
	return gcc
}

// SetUser sets the "user" edge to the User entity.
func (gcc *GiftCodeCreate) SetUser(u *User) *GiftCodeCreate {
	return gcc.SetUserID(u.ID)
}

// Mutation returns the GiftCodeMutation object of the builder.
func (gcc *GiftCodeCreate) Mutation() *GiftCodeMutation {
	return gcc.mutation
}

// Save creates the GiftCode in the database.
func (gcc *GiftCodeCreate) Save(ctx context.Context) (*GiftCode, error) {
	if err := gcc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, gcc.sqlSave, gcc.mutation, gcc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (gcc *GiftCodeCreate) SaveX(ctx context.Context) *GiftCode {
	v, err := gcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gcc *GiftCodeCreate) Exec(ctx context.Context) error {
	_, err := gcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gcc *GiftCodeCreate) ExecX(ctx context.Context) {
	if err := gcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (gcc *GiftCodeCreate) defaults() error {
	if _, ok := gcc.mutation.CreatedAt(); !ok {
		if giftcode.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized giftcode.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := giftcode.DefaultCreatedAt()
		gcc.mutation.SetCreatedAt(v)
	}
	if _, ok := gcc.mutation.UpdatedAt(); !ok {
		if giftcode.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized giftcode.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := giftcode.DefaultUpdatedAt()
		gcc.mutation.SetUpdatedAt(v)
	}
	if _, ok := gcc.mutation.Used(); !ok {
		v := giftcode.DefaultUsed
		gcc.mutation.SetUsed(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (gcc *GiftCodeCreate) check() error {
	if _, ok := gcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GiftCode.created_at"`)}
	}
	if _, ok := gcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GiftCode.updated_at"`)}
	}
	if _, ok := gcc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "GiftCode.code"`)}
	}
	if v, ok := gcc.mutation.Code(); ok {
		if err := giftcode.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "GiftCode.code": %w`, err)}
		}
	}
	if _, ok := gcc.mutation.ProductType(); !ok {
		return &ValidationError{Name: "product_type", err: errors.New(`ent: missing required field "GiftCode.product_type"`)}
	}
	if v, ok := gcc.mutation.ProductType(); ok {
		if err := giftcode.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "GiftCode.product_type": %w`, err)}
		}
	}
	if _, ok := gcc.mutation.Num(); !ok {
		return &ValidationError{Name: "num", err: errors.New(`ent: missing required field "GiftCode.num"`)}
	}
	if v, ok := gcc.mutation.Name(); ok {
		if err := giftcode.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "GiftCode.name": %w`, err)}
		}
	}
	if _, ok := gcc.mutation.Used(); !ok {
		return &ValidationError{Name: "used", err: errors.New(`ent: missing required field "GiftCode.used"`)}
	}
	if v, ok := gcc.mutation.UsedByEmail(); ok {
		if err := giftcode.UsedByEmailValidator(v); err != nil {
			return &ValidationError{Name: "used_by_email", err: fmt.Errorf(`ent: validator failed for field "GiftCode.used_by_email": %w`, err)}
		}
	}
	if v, ok := gcc.mutation.CreatedByEmail(); ok {
		if err := giftcode.CreatedByEmailValidator(v); err != nil {
			return &ValidationError{Name: "created_by_email", err: fmt.Errorf(`ent: validator failed for field "GiftCode.created_by_email": %w`, err)}
		}
	}
	return nil
}

func (gcc *GiftCodeCreate) sqlSave(ctx context.Context) (*GiftCode, error) {
	if err := gcc.check(); err != nil {
		return nil, err
	}
	_node, _spec := gcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, gcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	gcc.mutation.id = &_node.ID
	gcc.mutation.done = true
	return _node, nil
}

func (gcc *GiftCodeCreate) createSpec() (*GiftCode, *sqlgraph.CreateSpec) {
	var (
		_node = &GiftCode{config: gcc.config}
		_spec = sqlgraph.NewCreateSpec(giftcode.Table, sqlgraph.NewFieldSpec(giftcode.FieldID, field.TypeInt))
	)

	if id, ok := gcc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = gcc.conflict
	if value, ok := gcc.mutation.CreatedAt(); ok {
		_spec.SetField(giftcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := gcc.mutation.UpdatedAt(); ok {
		_spec.SetField(giftcode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := gcc.mutation.DeletedAt(); ok {
		_spec.SetField(giftcode.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := gcc.mutation.Code(); ok {
		_spec.SetField(giftcode.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := gcc.mutation.ProductType(); ok {
		_spec.SetField(giftcode.FieldProductType, field.TypeString, value)
		_node.ProductType = value
	}
	if value, ok := gcc.mutation.Num(); ok {
		_spec.SetField(giftcode.FieldNum, field.TypeInt64, value)
		_node.Num = value
	}
	if value, ok := gcc.mutation.Name(); ok {
		_spec.SetField(giftcode.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := gcc.mutation.Used(); ok {
		_spec.SetField(giftcode.FieldUsed, field.TypeBool, value)
		_node.Used = value
	}
	if value, ok := gcc.mutation.UsedByEmail(); ok {
		_spec.SetField(giftcode.FieldUsedByEmail, field.TypeString, value)
		_node.UsedByEmail = value
	}
	if value, ok := gcc.mutation.CreatedByEmail(); ok {
		_spec.SetField(giftcode.FieldCreatedByEmail, field.TypeString, value)
		_node.CreatedByEmail = value
	}
	if nodes := gcc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   giftcode.UserTable,
			Columns: []string{giftcode.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GiftCode.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GiftCodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (gcc *GiftCodeCreate) OnConflict(opts ...sql.ConflictOption) *GiftCodeUpsertOne {
	gcc.conflict = opts
	return &GiftCodeUpsertOne{
		create: gcc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GiftCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (gcc *GiftCodeCreate) OnConflictColumns(columns ...string) *GiftCodeUpsertOne {
	gcc.conflict = append(gcc.conflict, sql.ConflictColumns(columns...))
	return &GiftCodeUpsertOne{
		create: gcc,
	}
}

type (
	// GiftCodeUpsertOne is the builder for "upsert"-ing
	//  one GiftCode node.
	GiftCodeUpsertOne struct {
		create *GiftCodeCreate
	}

	// GiftCodeUpsert is the "OnConflict" setter.
	GiftCodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *GiftCodeUpsert) SetUpdatedAt(v time.Time) *GiftCodeUpsert {
	u.Set(giftcode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateUpdatedAt() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GiftCodeUpsert) SetDeletedAt(v time.Time) *GiftCodeUpsert {
	u.Set(giftcode.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateDeletedAt() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GiftCodeUpsert) ClearDeletedAt() *GiftCodeUpsert {
	u.SetNull(giftcode.FieldDeletedAt)
	return u
}

// SetCode sets the "code" field.
func (u *GiftCodeUpsert) SetCode(v string) *GiftCodeUpsert {
	u.Set(giftcode.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateCode() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldCode)
	return u
}

// SetProductType sets the "product_type" field.
func (u *GiftCodeUpsert) SetProductType(v string) *GiftCodeUpsert {
	u.Set(giftcode.FieldProductType, v)
	return u
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateProductType() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldProductType)
	return u
}

// SetNum sets the "num" field.
func (u *GiftCodeUpsert) SetNum(v int64) *GiftCodeUpsert {
	u.Set(giftcode.FieldNum, v)
	return u
}

// UpdateNum sets the "num" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateNum() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldNum)
	return u
}

// AddNum adds v to the "num" field.
func (u *GiftCodeUpsert) AddNum(v int64) *GiftCodeUpsert {
	u.Add(giftcode.FieldNum, v)
	return u
}

// SetName sets the "name" field.
func (u *GiftCodeUpsert) SetName(v string) *GiftCodeUpsert {
	u.Set(giftcode.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateName() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *GiftCodeUpsert) ClearName() *GiftCodeUpsert {
	u.SetNull(giftcode.FieldName)
	return u
}

// SetUsed sets the "used" field.
func (u *GiftCodeUpsert) SetUsed(v bool) *GiftCodeUpsert {
	u.Set(giftcode.FieldUsed, v)
	return u
}

// UpdateUsed sets the "used" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateUsed() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldUsed)
	return u
}

// SetUsedBy sets the "used_by" field.
func (u *GiftCodeUpsert) SetUsedBy(v int) *GiftCodeUpsert {
	u.Set(giftcode.FieldUsedBy, v)
	return u
}

// UpdateUsedBy sets the "used_by" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateUsedBy() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldUsedBy)
	return u
}

// ClearUsedBy clears the value of the "used_by" field.
func (u *GiftCodeUpsert) ClearUsedBy() *GiftCodeUpsert {
	u.SetNull(giftcode.FieldUsedBy)
	return u
}

// SetUsedByEmail sets the "used_by_email" field.
func (u *GiftCodeUpsert) SetUsedByEmail(v string) *GiftCodeUpsert {
	u.Set(giftcode.FieldUsedByEmail, v)
	return u
}

// UpdateUsedByEmail sets the "used_by_email" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateUsedByEmail() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldUsedByEmail)
	return u
}

// ClearUsedByEmail clears the value of the "used_by_email" field.
func (u *GiftCodeUpsert) ClearUsedByEmail() *GiftCodeUpsert {
	u.SetNull(giftcode.FieldUsedByEmail)
	return u
}

// SetCreatedByEmail sets the "created_by_email" field.
func (u *GiftCodeUpsert) SetCreatedByEmail(v string) *GiftCodeUpsert {
	u.Set(giftcode.FieldCreatedByEmail, v)
	return u
}

// UpdateCreatedByEmail sets the "created_by_email" field to the value that was provided on create.
func (u *GiftCodeUpsert) UpdateCreatedByEmail() *GiftCodeUpsert {
	u.SetExcluded(giftcode.FieldCreatedByEmail)
	return u
}

// ClearCreatedByEmail clears the value of the "created_by_email" field.
func (u *GiftCodeUpsert) ClearCreatedByEmail() *GiftCodeUpsert {
	u.SetNull(giftcode.FieldCreatedByEmail)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.GiftCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GiftCodeUpsertOne) UpdateNewValues() *GiftCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(giftcode.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GiftCode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GiftCodeUpsertOne) Ignore() *GiftCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GiftCodeUpsertOne) DoNothing() *GiftCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GiftCodeCreate.OnConflict
// documentation for more info.
func (u *GiftCodeUpsertOne) Update(set func(*GiftCodeUpsert)) *GiftCodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GiftCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GiftCodeUpsertOne) SetUpdatedAt(v time.Time) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateUpdatedAt() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GiftCodeUpsertOne) SetDeletedAt(v time.Time) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateDeletedAt() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GiftCodeUpsertOne) ClearDeletedAt() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *GiftCodeUpsertOne) SetCode(v string) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateCode() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateCode()
	})
}

// SetProductType sets the "product_type" field.
func (u *GiftCodeUpsertOne) SetProductType(v string) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetProductType(v)
	})
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateProductType() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateProductType()
	})
}

// SetNum sets the "num" field.
func (u *GiftCodeUpsertOne) SetNum(v int64) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetNum(v)
	})
}

// AddNum adds v to the "num" field.
func (u *GiftCodeUpsertOne) AddNum(v int64) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.AddNum(v)
	})
}

// UpdateNum sets the "num" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateNum() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateNum()
	})
}

// SetName sets the "name" field.
func (u *GiftCodeUpsertOne) SetName(v string) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateName() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *GiftCodeUpsertOne) ClearName() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearName()
	})
}

// SetUsed sets the "used" field.
func (u *GiftCodeUpsertOne) SetUsed(v bool) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetUsed(v)
	})
}

// UpdateUsed sets the "used" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateUsed() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateUsed()
	})
}

// SetUsedBy sets the "used_by" field.
func (u *GiftCodeUpsertOne) SetUsedBy(v int) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetUsedBy(v)
	})
}

// UpdateUsedBy sets the "used_by" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateUsedBy() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateUsedBy()
	})
}

// ClearUsedBy clears the value of the "used_by" field.
func (u *GiftCodeUpsertOne) ClearUsedBy() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearUsedBy()
	})
}

// SetUsedByEmail sets the "used_by_email" field.
func (u *GiftCodeUpsertOne) SetUsedByEmail(v string) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetUsedByEmail(v)
	})
}

// UpdateUsedByEmail sets the "used_by_email" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateUsedByEmail() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateUsedByEmail()
	})
}

// ClearUsedByEmail clears the value of the "used_by_email" field.
func (u *GiftCodeUpsertOne) ClearUsedByEmail() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearUsedByEmail()
	})
}

// SetCreatedByEmail sets the "created_by_email" field.
func (u *GiftCodeUpsertOne) SetCreatedByEmail(v string) *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetCreatedByEmail(v)
	})
}

// UpdateCreatedByEmail sets the "created_by_email" field to the value that was provided on create.
func (u *GiftCodeUpsertOne) UpdateCreatedByEmail() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateCreatedByEmail()
	})
}

// ClearCreatedByEmail clears the value of the "created_by_email" field.
func (u *GiftCodeUpsertOne) ClearCreatedByEmail() *GiftCodeUpsertOne {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearCreatedByEmail()
	})
}

// Exec executes the query.
func (u *GiftCodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GiftCodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GiftCodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GiftCodeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GiftCodeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *GiftCodeCreate) SetRawID(t int) *GiftCodeCreate {
	m.mutation.SetRawID(t)
	return m
}

// GiftCodeCreateBulk is the builder for creating many GiftCode entities in bulk.
type GiftCodeCreateBulk struct {
	config
	err      error
	builders []*GiftCodeCreate
	conflict []sql.ConflictOption
}

// Save creates the GiftCode entities in the database.
func (gccb *GiftCodeCreateBulk) Save(ctx context.Context) ([]*GiftCode, error) {
	if gccb.err != nil {
		return nil, gccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(gccb.builders))
	nodes := make([]*GiftCode, len(gccb.builders))
	mutators := make([]Mutator, len(gccb.builders))
	for i := range gccb.builders {
		func(i int, root context.Context) {
			builder := gccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GiftCodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, gccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = gccb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, gccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, gccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (gccb *GiftCodeCreateBulk) SaveX(ctx context.Context) []*GiftCode {
	v, err := gccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (gccb *GiftCodeCreateBulk) Exec(ctx context.Context) error {
	_, err := gccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (gccb *GiftCodeCreateBulk) ExecX(ctx context.Context) {
	if err := gccb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GiftCode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GiftCodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (gccb *GiftCodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *GiftCodeUpsertBulk {
	gccb.conflict = opts
	return &GiftCodeUpsertBulk{
		create: gccb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GiftCode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (gccb *GiftCodeCreateBulk) OnConflictColumns(columns ...string) *GiftCodeUpsertBulk {
	gccb.conflict = append(gccb.conflict, sql.ConflictColumns(columns...))
	return &GiftCodeUpsertBulk{
		create: gccb,
	}
}

// GiftCodeUpsertBulk is the builder for "upsert"-ing
// a bulk of GiftCode nodes.
type GiftCodeUpsertBulk struct {
	create *GiftCodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GiftCode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *GiftCodeUpsertBulk) UpdateNewValues() *GiftCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(giftcode.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GiftCode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GiftCodeUpsertBulk) Ignore() *GiftCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GiftCodeUpsertBulk) DoNothing() *GiftCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GiftCodeCreateBulk.OnConflict
// documentation for more info.
func (u *GiftCodeUpsertBulk) Update(set func(*GiftCodeUpsert)) *GiftCodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GiftCodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GiftCodeUpsertBulk) SetUpdatedAt(v time.Time) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateUpdatedAt() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *GiftCodeUpsertBulk) SetDeletedAt(v time.Time) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateDeletedAt() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *GiftCodeUpsertBulk) ClearDeletedAt() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCode sets the "code" field.
func (u *GiftCodeUpsertBulk) SetCode(v string) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateCode() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateCode()
	})
}

// SetProductType sets the "product_type" field.
func (u *GiftCodeUpsertBulk) SetProductType(v string) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetProductType(v)
	})
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateProductType() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateProductType()
	})
}

// SetNum sets the "num" field.
func (u *GiftCodeUpsertBulk) SetNum(v int64) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetNum(v)
	})
}

// AddNum adds v to the "num" field.
func (u *GiftCodeUpsertBulk) AddNum(v int64) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.AddNum(v)
	})
}

// UpdateNum sets the "num" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateNum() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateNum()
	})
}

// SetName sets the "name" field.
func (u *GiftCodeUpsertBulk) SetName(v string) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateName() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *GiftCodeUpsertBulk) ClearName() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearName()
	})
}

// SetUsed sets the "used" field.
func (u *GiftCodeUpsertBulk) SetUsed(v bool) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetUsed(v)
	})
}

// UpdateUsed sets the "used" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateUsed() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateUsed()
	})
}

// SetUsedBy sets the "used_by" field.
func (u *GiftCodeUpsertBulk) SetUsedBy(v int) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetUsedBy(v)
	})
}

// UpdateUsedBy sets the "used_by" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateUsedBy() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateUsedBy()
	})
}

// ClearUsedBy clears the value of the "used_by" field.
func (u *GiftCodeUpsertBulk) ClearUsedBy() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearUsedBy()
	})
}

// SetUsedByEmail sets the "used_by_email" field.
func (u *GiftCodeUpsertBulk) SetUsedByEmail(v string) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetUsedByEmail(v)
	})
}

// UpdateUsedByEmail sets the "used_by_email" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateUsedByEmail() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateUsedByEmail()
	})
}

// ClearUsedByEmail clears the value of the "used_by_email" field.
func (u *GiftCodeUpsertBulk) ClearUsedByEmail() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearUsedByEmail()
	})
}

// SetCreatedByEmail sets the "created_by_email" field.
func (u *GiftCodeUpsertBulk) SetCreatedByEmail(v string) *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.SetCreatedByEmail(v)
	})
}

// UpdateCreatedByEmail sets the "created_by_email" field to the value that was provided on create.
func (u *GiftCodeUpsertBulk) UpdateCreatedByEmail() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.UpdateCreatedByEmail()
	})
}

// ClearCreatedByEmail clears the value of the "created_by_email" field.
func (u *GiftCodeUpsertBulk) ClearCreatedByEmail() *GiftCodeUpsertBulk {
	return u.Update(func(s *GiftCodeUpsert) {
		s.ClearCreatedByEmail()
	})
}

// Exec executes the query.
func (u *GiftCodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GiftCodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GiftCodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GiftCodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
