// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/payment"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// PaymentUpdate is the builder for updating Payment entities.
type PaymentUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentMutation
}

// Where appends a list predicates to the PaymentUpdate builder.
func (pu *PaymentUpdate) Where(ps ...predicate.Payment) *PaymentUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *PaymentUpdate) SetUpdatedAt(t time.Time) *PaymentUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetDeletedAt sets the "deleted_at" field.
func (pu *PaymentUpdate) SetDeletedAt(t time.Time) *PaymentUpdate {
	pu.mutation.SetDeletedAt(t)
	return pu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableDeletedAt(t *time.Time) *PaymentUpdate {
	if t != nil {
		pu.SetDeletedAt(*t)
	}
	return pu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pu *PaymentUpdate) ClearDeletedAt() *PaymentUpdate {
	pu.mutation.ClearDeletedAt()
	return pu
}

// SetOrderNo sets the "order_no" field.
func (pu *PaymentUpdate) SetOrderNo(s string) *PaymentUpdate {
	pu.mutation.SetOrderNo(s)
	return pu
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableOrderNo(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetOrderNo(*s)
	}
	return pu
}

// SetUserID sets the "user_id" field.
func (pu *PaymentUpdate) SetUserID(i int) *PaymentUpdate {
	pu.mutation.SetUserID(i)
	return pu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableUserID(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetUserID(*i)
	}
	return pu
}

// ClearUserID clears the value of the "user_id" field.
func (pu *PaymentUpdate) ClearUserID() *PaymentUpdate {
	pu.mutation.ClearUserID()
	return pu
}

// SetProductType sets the "product_type" field.
func (pu *PaymentUpdate) SetProductType(s string) *PaymentUpdate {
	pu.mutation.SetProductType(s)
	return pu
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableProductType(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetProductType(*s)
	}
	return pu
}

// SetSkuID sets the "sku_id" field.
func (pu *PaymentUpdate) SetSkuID(i int) *PaymentUpdate {
	pu.mutation.ResetSkuID()
	pu.mutation.SetSkuID(i)
	return pu
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableSkuID(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetSkuID(*i)
	}
	return pu
}

// AddSkuID adds i to the "sku_id" field.
func (pu *PaymentUpdate) AddSkuID(i int) *PaymentUpdate {
	pu.mutation.AddSkuID(i)
	return pu
}

// ClearSkuID clears the value of the "sku_id" field.
func (pu *PaymentUpdate) ClearSkuID() *PaymentUpdate {
	pu.mutation.ClearSkuID()
	return pu
}

// SetSkuName sets the "sku_name" field.
func (pu *PaymentUpdate) SetSkuName(s string) *PaymentUpdate {
	pu.mutation.SetSkuName(s)
	return pu
}

// SetNillableSkuName sets the "sku_name" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableSkuName(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetSkuName(*s)
	}
	return pu
}

// ClearSkuName clears the value of the "sku_name" field.
func (pu *PaymentUpdate) ClearSkuName() *PaymentUpdate {
	pu.mutation.ClearSkuName()
	return pu
}

// SetNum sets the "num" field.
func (pu *PaymentUpdate) SetNum(i int64) *PaymentUpdate {
	pu.mutation.ResetNum()
	pu.mutation.SetNum(i)
	return pu
}

// SetNillableNum sets the "num" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableNum(i *int64) *PaymentUpdate {
	if i != nil {
		pu.SetNum(*i)
	}
	return pu
}

// AddNum adds i to the "num" field.
func (pu *PaymentUpdate) AddNum(i int64) *PaymentUpdate {
	pu.mutation.AddNum(i)
	return pu
}

// ClearNum clears the value of the "num" field.
func (pu *PaymentUpdate) ClearNum() *PaymentUpdate {
	pu.mutation.ClearNum()
	return pu
}

// SetQuantity sets the "quantity" field.
func (pu *PaymentUpdate) SetQuantity(i int) *PaymentUpdate {
	pu.mutation.ResetQuantity()
	pu.mutation.SetQuantity(i)
	return pu
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableQuantity(i *int) *PaymentUpdate {
	if i != nil {
		pu.SetQuantity(*i)
	}
	return pu
}

// AddQuantity adds i to the "quantity" field.
func (pu *PaymentUpdate) AddQuantity(i int) *PaymentUpdate {
	pu.mutation.AddQuantity(i)
	return pu
}

// SetAmount sets the "amount" field.
func (pu *PaymentUpdate) SetAmount(i int64) *PaymentUpdate {
	pu.mutation.ResetAmount()
	pu.mutation.SetAmount(i)
	return pu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableAmount(i *int64) *PaymentUpdate {
	if i != nil {
		pu.SetAmount(*i)
	}
	return pu
}

// AddAmount adds i to the "amount" field.
func (pu *PaymentUpdate) AddAmount(i int64) *PaymentUpdate {
	pu.mutation.AddAmount(i)
	return pu
}

// SetCurrency sets the "currency" field.
func (pu *PaymentUpdate) SetCurrency(s string) *PaymentUpdate {
	pu.mutation.SetCurrency(s)
	return pu
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableCurrency(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetCurrency(*s)
	}
	return pu
}

// ClearCurrency clears the value of the "currency" field.
func (pu *PaymentUpdate) ClearCurrency() *PaymentUpdate {
	pu.mutation.ClearCurrency()
	return pu
}

// SetPointsUsed sets the "points_used" field.
func (pu *PaymentUpdate) SetPointsUsed(i int64) *PaymentUpdate {
	pu.mutation.ResetPointsUsed()
	pu.mutation.SetPointsUsed(i)
	return pu
}

// SetNillablePointsUsed sets the "points_used" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePointsUsed(i *int64) *PaymentUpdate {
	if i != nil {
		pu.SetPointsUsed(*i)
	}
	return pu
}

// AddPointsUsed adds i to the "points_used" field.
func (pu *PaymentUpdate) AddPointsUsed(i int64) *PaymentUpdate {
	pu.mutation.AddPointsUsed(i)
	return pu
}

// SetChannel sets the "channel" field.
func (pu *PaymentUpdate) SetChannel(s string) *PaymentUpdate {
	pu.mutation.SetChannel(s)
	return pu
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableChannel(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetChannel(*s)
	}
	return pu
}

// ClearChannel clears the value of the "channel" field.
func (pu *PaymentUpdate) ClearChannel() *PaymentUpdate {
	pu.mutation.ClearChannel()
	return pu
}

// SetChannelTradeNo sets the "channel_trade_no" field.
func (pu *PaymentUpdate) SetChannelTradeNo(s string) *PaymentUpdate {
	pu.mutation.SetChannelTradeNo(s)
	return pu
}

// SetNillableChannelTradeNo sets the "channel_trade_no" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableChannelTradeNo(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetChannelTradeNo(*s)
	}
	return pu
}

// ClearChannelTradeNo clears the value of the "channel_trade_no" field.
func (pu *PaymentUpdate) ClearChannelTradeNo() *PaymentUpdate {
	pu.mutation.ClearChannelTradeNo()
	return pu
}

// SetPayURL sets the "pay_url" field.
func (pu *PaymentUpdate) SetPayURL(s string) *PaymentUpdate {
	pu.mutation.SetPayURL(s)
	return pu
}

// SetNillablePayURL sets the "pay_url" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillablePayURL(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetPayURL(*s)
	}
	return pu
}

// ClearPayURL clears the value of the "pay_url" field.
func (pu *PaymentUpdate) ClearPayURL() *PaymentUpdate {
	pu.mutation.ClearPayURL()
	return pu
}

// SetStatus sets the "status" field.
func (pu *PaymentUpdate) SetStatus(s string) *PaymentUpdate {
	pu.mutation.SetStatus(s)
	return pu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableStatus(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetStatus(*s)
	}
	return pu
}

// SetFailureReason sets the "failure_reason" field.
func (pu *PaymentUpdate) SetFailureReason(s string) *PaymentUpdate {
	pu.mutation.SetFailureReason(s)
	return pu
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableFailureReason(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetFailureReason(*s)
	}
	return pu
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (pu *PaymentUpdate) ClearFailureReason() *PaymentUpdate {
	pu.mutation.ClearFailureReason()
	return pu
}

// SetEmail sets the "email" field.
func (pu *PaymentUpdate) SetEmail(s string) *PaymentUpdate {
	pu.mutation.SetEmail(s)
	return pu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableEmail(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetEmail(*s)
	}
	return pu
}

// ClearEmail clears the value of the "email" field.
func (pu *PaymentUpdate) ClearEmail() *PaymentUpdate {
	pu.mutation.ClearEmail()
	return pu
}

// SetResumeTicket sets the "resume_ticket" field.
func (pu *PaymentUpdate) SetResumeTicket(s string) *PaymentUpdate {
	pu.mutation.SetResumeTicket(s)
	return pu
}

// SetNillableResumeTicket sets the "resume_ticket" field if the given value is not nil.
func (pu *PaymentUpdate) SetNillableResumeTicket(s *string) *PaymentUpdate {
	if s != nil {
		pu.SetResumeTicket(*s)
	}
	return pu
}

// ClearResumeTicket clears the value of the "resume_ticket" field.
func (pu *PaymentUpdate) ClearResumeTicket() *PaymentUpdate {
	pu.mutation.ClearResumeTicket()
	return pu
}

// SetUser sets the "user" edge to the User entity.
func (pu *PaymentUpdate) SetUser(u *User) *PaymentUpdate {
	return pu.SetUserID(u.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (pu *PaymentUpdate) Mutation() *PaymentMutation {
	return pu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (pu *PaymentUpdate) ClearUser() *PaymentUpdate {
	pu.mutation.ClearUser()
	return pu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PaymentUpdate) Save(ctx context.Context) (int, error) {
	if err := pu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PaymentUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PaymentUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PaymentUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *PaymentUpdate) defaults() error {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		if payment.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized payment.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := payment.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pu *PaymentUpdate) check() error {
	if v, ok := pu.mutation.OrderNo(); ok {
		if err := payment.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Payment.order_no": %w`, err)}
		}
	}
	if v, ok := pu.mutation.ProductType(); ok {
		if err := payment.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "Payment.product_type": %w`, err)}
		}
	}
	if v, ok := pu.mutation.SkuName(); ok {
		if err := payment.SkuNameValidator(v); err != nil {
			return &ValidationError{Name: "sku_name", err: fmt.Errorf(`ent: validator failed for field "Payment.sku_name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Currency(); ok {
		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Channel(); ok {
		if err := payment.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Payment.channel": %w`, err)}
		}
	}
	if v, ok := pu.mutation.ChannelTradeNo(); ok {
		if err := payment.ChannelTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "channel_trade_no", err: fmt.Errorf(`ent: validator failed for field "Payment.channel_trade_no": %w`, err)}
		}
	}
	if v, ok := pu.mutation.PayURL(); ok {
		if err := payment.PayURLValidator(v); err != nil {
			return &ValidationError{Name: "pay_url", err: fmt.Errorf(`ent: validator failed for field "Payment.pay_url": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if v, ok := pu.mutation.FailureReason(); ok {
		if err := payment.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "Payment.failure_reason": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Email(); ok {
		if err := payment.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Payment.email": %w`, err)}
		}
	}
	if v, ok := pu.mutation.ResumeTicket(); ok {
		if err := payment.ResumeTicketValidator(v); err != nil {
			return &ValidationError{Name: "resume_ticket", err: fmt.Errorf(`ent: validator failed for field "Payment.resume_ticket": %w`, err)}
		}
	}
	return nil
}

func (pu *PaymentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.DeletedAt(); ok {
		_spec.SetField(payment.FieldDeletedAt, field.TypeTime, value)
	}
	if pu.mutation.DeletedAtCleared() {
		_spec.ClearField(payment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := pu.mutation.OrderNo(); ok {
		_spec.SetField(payment.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := pu.mutation.ProductType(); ok {
		_spec.SetField(payment.FieldProductType, field.TypeString, value)
	}
	if value, ok := pu.mutation.SkuID(); ok {
		_spec.SetField(payment.FieldSkuID, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedSkuID(); ok {
		_spec.AddField(payment.FieldSkuID, field.TypeInt, value)
	}
	if pu.mutation.SkuIDCleared() {
		_spec.ClearField(payment.FieldSkuID, field.TypeInt)
	}
	if value, ok := pu.mutation.SkuName(); ok {
		_spec.SetField(payment.FieldSkuName, field.TypeString, value)
	}
	if pu.mutation.SkuNameCleared() {
		_spec.ClearField(payment.FieldSkuName, field.TypeString)
	}
	if value, ok := pu.mutation.Num(); ok {
		_spec.SetField(payment.FieldNum, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedNum(); ok {
		_spec.AddField(payment.FieldNum, field.TypeInt64, value)
	}
	if pu.mutation.NumCleared() {
		_spec.ClearField(payment.FieldNum, field.TypeInt64)
	}
	if value, ok := pu.mutation.Quantity(); ok {
		_spec.SetField(payment.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedQuantity(); ok {
		_spec.AddField(payment.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := pu.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
	}
	if pu.mutation.CurrencyCleared() {
		_spec.ClearField(payment.FieldCurrency, field.TypeString)
	}
	if value, ok := pu.mutation.PointsUsed(); ok {
		_spec.SetField(payment.FieldPointsUsed, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedPointsUsed(); ok {
		_spec.AddField(payment.FieldPointsUsed, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.Channel(); ok {
		_spec.SetField(payment.FieldChannel, field.TypeString, value)
	}
	if pu.mutation.ChannelCleared() {
		_spec.ClearField(payment.FieldChannel, field.TypeString)
	}
	if value, ok := pu.mutation.ChannelTradeNo(); ok {
		_spec.SetField(payment.FieldChannelTradeNo, field.TypeString, value)
	}
	if pu.mutation.ChannelTradeNoCleared() {
		_spec.ClearField(payment.FieldChannelTradeNo, field.TypeString)
	}
	if value, ok := pu.mutation.PayURL(); ok {
		_spec.SetField(payment.FieldPayURL, field.TypeString, value)
	}
	if pu.mutation.PayURLCleared() {
		_spec.ClearField(payment.FieldPayURL, field.TypeString)
	}
	if value, ok := pu.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeString, value)
	}
	if value, ok := pu.mutation.FailureReason(); ok {
		_spec.SetField(payment.FieldFailureReason, field.TypeString, value)
	}
	if pu.mutation.FailureReasonCleared() {
		_spec.ClearField(payment.FieldFailureReason, field.TypeString)
	}
	if value, ok := pu.mutation.Email(); ok {
		_spec.SetField(payment.FieldEmail, field.TypeString, value)
	}
	if pu.mutation.EmailCleared() {
		_spec.ClearField(payment.FieldEmail, field.TypeString)
	}
	if value, ok := pu.mutation.ResumeTicket(); ok {
		_spec.SetField(payment.FieldResumeTicket, field.TypeString, value)
	}
	if pu.mutation.ResumeTicketCleared() {
		_spec.ClearField(payment.FieldResumeTicket, field.TypeString)
	}
	if pu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PaymentUpdateOne is the builder for updating a single Payment entity.
type PaymentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *PaymentUpdateOne) SetUpdatedAt(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetDeletedAt sets the "deleted_at" field.
func (puo *PaymentUpdateOne) SetDeletedAt(t time.Time) *PaymentUpdateOne {
	puo.mutation.SetDeletedAt(t)
	return puo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableDeletedAt(t *time.Time) *PaymentUpdateOne {
	if t != nil {
		puo.SetDeletedAt(*t)
	}
	return puo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (puo *PaymentUpdateOne) ClearDeletedAt() *PaymentUpdateOne {
	puo.mutation.ClearDeletedAt()
	return puo
}

// SetOrderNo sets the "order_no" field.
func (puo *PaymentUpdateOne) SetOrderNo(s string) *PaymentUpdateOne {
	puo.mutation.SetOrderNo(s)
	return puo
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableOrderNo(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetOrderNo(*s)
	}
	return puo
}

// SetUserID sets the "user_id" field.
func (puo *PaymentUpdateOne) SetUserID(i int) *PaymentUpdateOne {
	puo.mutation.SetUserID(i)
	return puo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableUserID(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetUserID(*i)
	}
	return puo
}

// ClearUserID clears the value of the "user_id" field.
func (puo *PaymentUpdateOne) ClearUserID() *PaymentUpdateOne {
	puo.mutation.ClearUserID()
	return puo
}

// SetProductType sets the "product_type" field.
func (puo *PaymentUpdateOne) SetProductType(s string) *PaymentUpdateOne {
	puo.mutation.SetProductType(s)
	return puo
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableProductType(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetProductType(*s)
	}
	return puo
}

// SetSkuID sets the "sku_id" field.
func (puo *PaymentUpdateOne) SetSkuID(i int) *PaymentUpdateOne {
	puo.mutation.ResetSkuID()
	puo.mutation.SetSkuID(i)
	return puo
}

// SetNillableSkuID sets the "sku_id" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableSkuID(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetSkuID(*i)
	}
	return puo
}

// AddSkuID adds i to the "sku_id" field.
func (puo *PaymentUpdateOne) AddSkuID(i int) *PaymentUpdateOne {
	puo.mutation.AddSkuID(i)
	return puo
}

// ClearSkuID clears the value of the "sku_id" field.
func (puo *PaymentUpdateOne) ClearSkuID() *PaymentUpdateOne {
	puo.mutation.ClearSkuID()
	return puo
}

// SetSkuName sets the "sku_name" field.
func (puo *PaymentUpdateOne) SetSkuName(s string) *PaymentUpdateOne {
	puo.mutation.SetSkuName(s)
	return puo
}

// SetNillableSkuName sets the "sku_name" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableSkuName(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetSkuName(*s)
	}
	return puo
}

// ClearSkuName clears the value of the "sku_name" field.
func (puo *PaymentUpdateOne) ClearSkuName() *PaymentUpdateOne {
	puo.mutation.ClearSkuName()
	return puo
}

// SetNum sets the "num" field.
func (puo *PaymentUpdateOne) SetNum(i int64) *PaymentUpdateOne {
	puo.mutation.ResetNum()
	puo.mutation.SetNum(i)
	return puo
}

// SetNillableNum sets the "num" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableNum(i *int64) *PaymentUpdateOne {
	if i != nil {
		puo.SetNum(*i)
	}
	return puo
}

// AddNum adds i to the "num" field.
func (puo *PaymentUpdateOne) AddNum(i int64) *PaymentUpdateOne {
	puo.mutation.AddNum(i)
	return puo
}

// ClearNum clears the value of the "num" field.
func (puo *PaymentUpdateOne) ClearNum() *PaymentUpdateOne {
	puo.mutation.ClearNum()
	return puo
}

// SetQuantity sets the "quantity" field.
func (puo *PaymentUpdateOne) SetQuantity(i int) *PaymentUpdateOne {
	puo.mutation.ResetQuantity()
	puo.mutation.SetQuantity(i)
	return puo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableQuantity(i *int) *PaymentUpdateOne {
	if i != nil {
		puo.SetQuantity(*i)
	}
	return puo
}

// AddQuantity adds i to the "quantity" field.
func (puo *PaymentUpdateOne) AddQuantity(i int) *PaymentUpdateOne {
	puo.mutation.AddQuantity(i)
	return puo
}

// SetAmount sets the "amount" field.
func (puo *PaymentUpdateOne) SetAmount(i int64) *PaymentUpdateOne {
	puo.mutation.ResetAmount()
	puo.mutation.SetAmount(i)
	return puo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableAmount(i *int64) *PaymentUpdateOne {
	if i != nil {
		puo.SetAmount(*i)
	}
	return puo
}

// AddAmount adds i to the "amount" field.
func (puo *PaymentUpdateOne) AddAmount(i int64) *PaymentUpdateOne {
	puo.mutation.AddAmount(i)
	return puo
}

// SetCurrency sets the "currency" field.
func (puo *PaymentUpdateOne) SetCurrency(s string) *PaymentUpdateOne {
	puo.mutation.SetCurrency(s)
	return puo
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableCurrency(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetCurrency(*s)
	}
	return puo
}

// ClearCurrency clears the value of the "currency" field.
func (puo *PaymentUpdateOne) ClearCurrency() *PaymentUpdateOne {
	puo.mutation.ClearCurrency()
	return puo
}

// SetPointsUsed sets the "points_used" field.
func (puo *PaymentUpdateOne) SetPointsUsed(i int64) *PaymentUpdateOne {
	puo.mutation.ResetPointsUsed()
	puo.mutation.SetPointsUsed(i)
	return puo
}

// SetNillablePointsUsed sets the "points_used" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePointsUsed(i *int64) *PaymentUpdateOne {
	if i != nil {
		puo.SetPointsUsed(*i)
	}
	return puo
}

// AddPointsUsed adds i to the "points_used" field.
func (puo *PaymentUpdateOne) AddPointsUsed(i int64) *PaymentUpdateOne {
	puo.mutation.AddPointsUsed(i)
	return puo
}

// SetChannel sets the "channel" field.
func (puo *PaymentUpdateOne) SetChannel(s string) *PaymentUpdateOne {
	puo.mutation.SetChannel(s)
	return puo
}

// SetNillableChannel sets the "channel" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableChannel(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetChannel(*s)
	}
	return puo
}

// ClearChannel clears the value of the "channel" field.
func (puo *PaymentUpdateOne) ClearChannel() *PaymentUpdateOne {
	puo.mutation.ClearChannel()
	return puo
}

// SetChannelTradeNo sets the "channel_trade_no" field.
func (puo *PaymentUpdateOne) SetChannelTradeNo(s string) *PaymentUpdateOne {
	puo.mutation.SetChannelTradeNo(s)
	return puo
}

// SetNillableChannelTradeNo sets the "channel_trade_no" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableChannelTradeNo(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetChannelTradeNo(*s)
	}
	return puo
}

// ClearChannelTradeNo clears the value of the "channel_trade_no" field.
func (puo *PaymentUpdateOne) ClearChannelTradeNo() *PaymentUpdateOne {
	puo.mutation.ClearChannelTradeNo()
	return puo
}

// SetPayURL sets the "pay_url" field.
func (puo *PaymentUpdateOne) SetPayURL(s string) *PaymentUpdateOne {
	puo.mutation.SetPayURL(s)
	return puo
}

// SetNillablePayURL sets the "pay_url" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillablePayURL(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetPayURL(*s)
	}
	return puo
}

// ClearPayURL clears the value of the "pay_url" field.
func (puo *PaymentUpdateOne) ClearPayURL() *PaymentUpdateOne {
	puo.mutation.ClearPayURL()
	return puo
}

// SetStatus sets the "status" field.
func (puo *PaymentUpdateOne) SetStatus(s string) *PaymentUpdateOne {
	puo.mutation.SetStatus(s)
	return puo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableStatus(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetStatus(*s)
	}
	return puo
}

// SetFailureReason sets the "failure_reason" field.
func (puo *PaymentUpdateOne) SetFailureReason(s string) *PaymentUpdateOne {
	puo.mutation.SetFailureReason(s)
	return puo
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableFailureReason(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetFailureReason(*s)
	}
	return puo
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (puo *PaymentUpdateOne) ClearFailureReason() *PaymentUpdateOne {
	puo.mutation.ClearFailureReason()
	return puo
}

// SetEmail sets the "email" field.
func (puo *PaymentUpdateOne) SetEmail(s string) *PaymentUpdateOne {
	puo.mutation.SetEmail(s)
	return puo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableEmail(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetEmail(*s)
	}
	return puo
}

// ClearEmail clears the value of the "email" field.
func (puo *PaymentUpdateOne) ClearEmail() *PaymentUpdateOne {
	puo.mutation.ClearEmail()
	return puo
}

// SetResumeTicket sets the "resume_ticket" field.
func (puo *PaymentUpdateOne) SetResumeTicket(s string) *PaymentUpdateOne {
	puo.mutation.SetResumeTicket(s)
	return puo
}

// SetNillableResumeTicket sets the "resume_ticket" field if the given value is not nil.
func (puo *PaymentUpdateOne) SetNillableResumeTicket(s *string) *PaymentUpdateOne {
	if s != nil {
		puo.SetResumeTicket(*s)
	}
	return puo
}

// ClearResumeTicket clears the value of the "resume_ticket" field.
func (puo *PaymentUpdateOne) ClearResumeTicket() *PaymentUpdateOne {
	puo.mutation.ClearResumeTicket()
	return puo
}

// SetUser sets the "user" edge to the User entity.
func (puo *PaymentUpdateOne) SetUser(u *User) *PaymentUpdateOne {
	return puo.SetUserID(u.ID)
}

// Mutation returns the PaymentMutation object of the builder.
func (puo *PaymentUpdateOne) Mutation() *PaymentMutation {
	return puo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (puo *PaymentUpdateOne) ClearUser() *PaymentUpdateOne {
	puo.mutation.ClearUser()
	return puo
}

// Where appends a list predicates to the PaymentUpdate builder.
func (puo *PaymentUpdateOne) Where(ps ...predicate.Payment) *PaymentUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PaymentUpdateOne) Select(field string, fields ...string) *PaymentUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Payment entity.
func (puo *PaymentUpdateOne) Save(ctx context.Context) (*Payment, error) {
	if err := puo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PaymentUpdateOne) SaveX(ctx context.Context) *Payment {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PaymentUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PaymentUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *PaymentUpdateOne) defaults() error {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		if payment.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized payment.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := payment.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (puo *PaymentUpdateOne) check() error {
	if v, ok := puo.mutation.OrderNo(); ok {
		if err := payment.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Payment.order_no": %w`, err)}
		}
	}
	if v, ok := puo.mutation.ProductType(); ok {
		if err := payment.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "Payment.product_type": %w`, err)}
		}
	}
	if v, ok := puo.mutation.SkuName(); ok {
		if err := payment.SkuNameValidator(v); err != nil {
			return &ValidationError{Name: "sku_name", err: fmt.Errorf(`ent: validator failed for field "Payment.sku_name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Currency(); ok {
		if err := payment.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Payment.currency": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Channel(); ok {
		if err := payment.ChannelValidator(v); err != nil {
			return &ValidationError{Name: "channel", err: fmt.Errorf(`ent: validator failed for field "Payment.channel": %w`, err)}
		}
	}
	if v, ok := puo.mutation.ChannelTradeNo(); ok {
		if err := payment.ChannelTradeNoValidator(v); err != nil {
			return &ValidationError{Name: "channel_trade_no", err: fmt.Errorf(`ent: validator failed for field "Payment.channel_trade_no": %w`, err)}
		}
	}
	if v, ok := puo.mutation.PayURL(); ok {
		if err := payment.PayURLValidator(v); err != nil {
			return &ValidationError{Name: "pay_url", err: fmt.Errorf(`ent: validator failed for field "Payment.pay_url": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Status(); ok {
		if err := payment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Payment.status": %w`, err)}
		}
	}
	if v, ok := puo.mutation.FailureReason(); ok {
		if err := payment.FailureReasonValidator(v); err != nil {
			return &ValidationError{Name: "failure_reason", err: fmt.Errorf(`ent: validator failed for field "Payment.failure_reason": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Email(); ok {
		if err := payment.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Payment.email": %w`, err)}
		}
	}
	if v, ok := puo.mutation.ResumeTicket(); ok {
		if err := payment.ResumeTicketValidator(v); err != nil {
			return &ValidationError{Name: "resume_ticket", err: fmt.Errorf(`ent: validator failed for field "Payment.resume_ticket": %w`, err)}
		}
	}
	return nil
}

func (puo *PaymentUpdateOne) sqlSave(ctx context.Context) (_node *Payment, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(payment.Table, payment.Columns, sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Payment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, payment.FieldID)
		for _, f := range fields {
			if !payment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != payment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(payment.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.DeletedAt(); ok {
		_spec.SetField(payment.FieldDeletedAt, field.TypeTime, value)
	}
	if puo.mutation.DeletedAtCleared() {
		_spec.ClearField(payment.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := puo.mutation.OrderNo(); ok {
		_spec.SetField(payment.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := puo.mutation.ProductType(); ok {
		_spec.SetField(payment.FieldProductType, field.TypeString, value)
	}
	if value, ok := puo.mutation.SkuID(); ok {
		_spec.SetField(payment.FieldSkuID, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedSkuID(); ok {
		_spec.AddField(payment.FieldSkuID, field.TypeInt, value)
	}
	if puo.mutation.SkuIDCleared() {
		_spec.ClearField(payment.FieldSkuID, field.TypeInt)
	}
	if value, ok := puo.mutation.SkuName(); ok {
		_spec.SetField(payment.FieldSkuName, field.TypeString, value)
	}
	if puo.mutation.SkuNameCleared() {
		_spec.ClearField(payment.FieldSkuName, field.TypeString)
	}
	if value, ok := puo.mutation.Num(); ok {
		_spec.SetField(payment.FieldNum, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedNum(); ok {
		_spec.AddField(payment.FieldNum, field.TypeInt64, value)
	}
	if puo.mutation.NumCleared() {
		_spec.ClearField(payment.FieldNum, field.TypeInt64)
	}
	if value, ok := puo.mutation.Quantity(); ok {
		_spec.SetField(payment.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedQuantity(); ok {
		_spec.AddField(payment.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := puo.mutation.Amount(); ok {
		_spec.SetField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedAmount(); ok {
		_spec.AddField(payment.FieldAmount, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.Currency(); ok {
		_spec.SetField(payment.FieldCurrency, field.TypeString, value)
	}
	if puo.mutation.CurrencyCleared() {
		_spec.ClearField(payment.FieldCurrency, field.TypeString)
	}
	if value, ok := puo.mutation.PointsUsed(); ok {
		_spec.SetField(payment.FieldPointsUsed, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedPointsUsed(); ok {
		_spec.AddField(payment.FieldPointsUsed, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.Channel(); ok {
		_spec.SetField(payment.FieldChannel, field.TypeString, value)
	}
	if puo.mutation.ChannelCleared() {
		_spec.ClearField(payment.FieldChannel, field.TypeString)
	}
	if value, ok := puo.mutation.ChannelTradeNo(); ok {
		_spec.SetField(payment.FieldChannelTradeNo, field.TypeString, value)
	}
	if puo.mutation.ChannelTradeNoCleared() {
		_spec.ClearField(payment.FieldChannelTradeNo, field.TypeString)
	}
	if value, ok := puo.mutation.PayURL(); ok {
		_spec.SetField(payment.FieldPayURL, field.TypeString, value)
	}
	if puo.mutation.PayURLCleared() {
		_spec.ClearField(payment.FieldPayURL, field.TypeString)
	}
	if value, ok := puo.mutation.Status(); ok {
		_spec.SetField(payment.FieldStatus, field.TypeString, value)
	}
	if value, ok := puo.mutation.FailureReason(); ok {
		_spec.SetField(payment.FieldFailureReason, field.TypeString, value)
	}
	if puo.mutation.FailureReasonCleared() {
		_spec.ClearField(payment.FieldFailureReason, field.TypeString)
	}
	if value, ok := puo.mutation.Email(); ok {
		_spec.SetField(payment.FieldEmail, field.TypeString, value)
	}
	if puo.mutation.EmailCleared() {
		_spec.ClearField(payment.FieldEmail, field.TypeString)
	}
	if value, ok := puo.mutation.ResumeTicket(); ok {
		_spec.SetField(payment.FieldResumeTicket, field.TypeString, value)
	}
	if puo.mutation.ResumeTicketCleared() {
		_spec.ClearField(payment.FieldResumeTicket, field.TypeString)
	}
	if puo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   payment.UserTable,
			Columns: []string{payment.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Payment{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{payment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
