// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/payment"
	"github.com/cloudreve/Cloudreve/v4/ent/pointsledger"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
)

// PointsLedgerCreate is the builder for creating a PointsLedger entity.
type PointsLedgerCreate struct {
	config
	mutation *PointsLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (plc *PointsLedgerCreate) SetCreatedAt(t time.Time) *PointsLedgerCreate {
	plc.mutation.SetCreatedAt(t)
	return plc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (plc *PointsLedgerCreate) SetNillableCreatedAt(t *time.Time) *PointsLedgerCreate {
	if t != nil {
		plc.SetCreatedAt(*t)
	}
	return plc
}

// SetUpdatedAt sets the "updated_at" field.
func (plc *PointsLedgerCreate) SetUpdatedAt(t time.Time) *PointsLedgerCreate {
	plc.mutation.SetUpdatedAt(t)
	return plc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (plc *PointsLedgerCreate) SetNillableUpdatedAt(t *time.Time) *PointsLedgerCreate {
	if t != nil {
		plc.SetUpdatedAt(*t)
	}
	return plc
}

// SetDeletedAt sets the "deleted_at" field.
func (plc *PointsLedgerCreate) SetDeletedAt(t time.Time) *PointsLedgerCreate {
	plc.mutation.SetDeletedAt(t)
	return plc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (plc *PointsLedgerCreate) SetNillableDeletedAt(t *time.Time) *PointsLedgerCreate {
	if t != nil {
		plc.SetDeletedAt(*t)
	}
	return plc
}

// SetUserID sets the "user_id" field.
func (plc *PointsLedgerCreate) SetUserID(i int) *PointsLedgerCreate {
	plc.mutation.SetUserID(i)
	return plc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (plc *PointsLedgerCreate) SetNillableUserID(i *int) *PointsLedgerCreate {
	if i != nil {
		plc.SetUserID(*i)
	}
	return plc
}

// SetDelta sets the "delta" field.
func (plc *PointsLedgerCreate) SetDelta(i int64) *PointsLedgerCreate {
	plc.mutation.SetDelta(i)
	return plc
}

// SetBalanceAfter sets the "balance_after" field.
func (plc *PointsLedgerCreate) SetBalanceAfter(i int64) *PointsLedgerCreate {
	plc.mutation.SetBalanceAfter(i)
	return plc
}

// SetReason sets the "reason" field.
func (plc *PointsLedgerCreate) SetReason(s string) *PointsLedgerCreate {
	plc.mutation.SetReason(s)
	return plc
}

// SetNote sets the "note" field.
func (plc *PointsLedgerCreate) SetNote(s string) *PointsLedgerCreate {
	plc.mutation.SetNote(s)
	return plc
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (plc *PointsLedgerCreate) SetNillableNote(s *string) *PointsLedgerCreate {
	if s != nil {
		plc.SetNote(*s)
	}
	return plc
}

// SetPaymentID sets the "payment_id" field.
func (plc *PointsLedgerCreate) SetPaymentID(i int) *PointsLedgerCreate {
	plc.mutation.SetPaymentID(i)
	return plc
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (plc *PointsLedgerCreate) SetNillablePaymentID(i *int) *PointsLedgerCreate {
	if i != nil {
		plc.SetPaymentID(*i)
	}
	return plc
}

// SetUser sets the "user" edge to the User entity.
func (plc *PointsLedgerCreate) SetUser(u *User) *PointsLedgerCreate {
	return plc.SetUserID(u.ID)
}

// SetPayment sets the "payment" edge to the Payment entity.
func (plc *PointsLedgerCreate) SetPayment(p *Payment) *PointsLedgerCreate {
	return plc.SetPaymentID(p.ID)
}

// Mutation returns the PointsLedgerMutation object of the builder.
func (plc *PointsLedgerCreate) Mutation() *PointsLedgerMutation {
	return plc.mutation
}

// Save creates the PointsLedger in the database.
func (plc *PointsLedgerCreate) Save(ctx context.Context) (*PointsLedger, error) {
	if err := plc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, plc.sqlSave, plc.mutation, plc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (plc *PointsLedgerCreate) SaveX(ctx context.Context) *PointsLedger {
	v, err := plc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (plc *PointsLedgerCreate) Exec(ctx context.Context) error {
	_, err := plc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plc *PointsLedgerCreate) ExecX(ctx context.Context) {
	if err := plc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (plc *PointsLedgerCreate) defaults() error {
	if _, ok := plc.mutation.CreatedAt(); !ok {
		if pointsledger.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized pointsledger.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := pointsledger.DefaultCreatedAt()
		plc.mutation.SetCreatedAt(v)
	}
	if _, ok := plc.mutation.UpdatedAt(); !ok {
		if pointsledger.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pointsledger.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pointsledger.DefaultUpdatedAt()
		plc.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (plc *PointsLedgerCreate) check() error {
	if _, ok := plc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PointsLedger.created_at"`)}
	}
	if _, ok := plc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PointsLedger.updated_at"`)}
	}
	if _, ok := plc.mutation.Delta(); !ok {
		return &ValidationError{Name: "delta", err: errors.New(`ent: missing required field "PointsLedger.delta"`)}
	}
	if _, ok := plc.mutation.BalanceAfter(); !ok {
		return &ValidationError{Name: "balance_after", err: errors.New(`ent: missing required field "PointsLedger.balance_after"`)}
	}
	if _, ok := plc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "PointsLedger.reason"`)}
	}
	if v, ok := plc.mutation.Reason(); ok {
		if err := pointsledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "PointsLedger.reason": %w`, err)}
		}
	}
	if v, ok := plc.mutation.Note(); ok {
		if err := pointsledger.NoteValidator(v); err != nil {
			return &ValidationError{Name: "note", err: fmt.Errorf(`ent: validator failed for field "PointsLedger.note": %w`, err)}
		}
	}
	return nil
}

func (plc *PointsLedgerCreate) sqlSave(ctx context.Context) (*PointsLedger, error) {
	if err := plc.check(); err != nil {
		return nil, err
	}
	_node, _spec := plc.createSpec()
	if err := sqlgraph.CreateNode(ctx, plc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	plc.mutation.id = &_node.ID
	plc.mutation.done = true
	return _node, nil
}

func (plc *PointsLedgerCreate) createSpec() (*PointsLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &PointsLedger{config: plc.config}
		_spec = sqlgraph.NewCreateSpec(pointsledger.Table, sqlgraph.NewFieldSpec(pointsledger.FieldID, field.TypeInt))
	)

	if id, ok := plc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = plc.conflict
	if value, ok := plc.mutation.CreatedAt(); ok {
		_spec.SetField(pointsledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := plc.mutation.UpdatedAt(); ok {
		_spec.SetField(pointsledger.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := plc.mutation.DeletedAt(); ok {
		_spec.SetField(pointsledger.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := plc.mutation.Delta(); ok {
		_spec.SetField(pointsledger.FieldDelta, field.TypeInt64, value)
		_node.Delta = value
	}
	if value, ok := plc.mutation.BalanceAfter(); ok {
		_spec.SetField(pointsledger.FieldBalanceAfter, field.TypeInt64, value)
		_node.BalanceAfter = value
	}
	if value, ok := plc.mutation.Reason(); ok {
		_spec.SetField(pointsledger.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := plc.mutation.Note(); ok {
		_spec.SetField(pointsledger.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if nodes := plc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pointsledger.UserTable,
			Columns: []string{pointsledger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := plc.mutation.PaymentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pointsledger.PaymentTable,
			Columns: []string{pointsledger.PaymentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(payment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PaymentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PointsLedger.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PointsLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (plc *PointsLedgerCreate) OnConflict(opts ...sql.ConflictOption) *PointsLedgerUpsertOne {
	plc.conflict = opts
	return &PointsLedgerUpsertOne{
		create: plc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PointsLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (plc *PointsLedgerCreate) OnConflictColumns(columns ...string) *PointsLedgerUpsertOne {
	plc.conflict = append(plc.conflict, sql.ConflictColumns(columns...))
	return &PointsLedgerUpsertOne{
		create: plc,
	}
}

type (
	// PointsLedgerUpsertOne is the builder for "upsert"-ing
	//  one PointsLedger node.
	PointsLedgerUpsertOne struct {
		create *PointsLedgerCreate
	}

	// PointsLedgerUpsert is the "OnConflict" setter.
	PointsLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PointsLedgerUpsert) SetUpdatedAt(v time.Time) *PointsLedgerUpsert {
	u.Set(pointsledger.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PointsLedgerUpsert) UpdateUpdatedAt() *PointsLedgerUpsert {
	u.SetExcluded(pointsledger.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PointsLedgerUpsert) SetDeletedAt(v time.Time) *PointsLedgerUpsert {
	u.Set(pointsledger.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PointsLedgerUpsert) UpdateDeletedAt() *PointsLedgerUpsert {
	u.SetExcluded(pointsledger.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PointsLedgerUpsert) ClearDeletedAt() *PointsLedgerUpsert {
	u.SetNull(pointsledger.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PointsLedgerUpsert) SetUserID(v int) *PointsLedgerUpsert {
	u.Set(pointsledger.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PointsLedgerUpsert) UpdateUserID() *PointsLedgerUpsert {
	u.SetExcluded(pointsledger.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *PointsLedgerUpsert) ClearUserID() *PointsLedgerUpsert {
	u.SetNull(pointsledger.FieldUserID)
	return u
}

// SetDelta sets the "delta" field.
func (u *PointsLedgerUpsert) SetDelta(v int64) *PointsLedgerUpsert {
	u.Set(pointsledger.FieldDelta, v)
	return u
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *PointsLedgerUpsert) UpdateDelta() *PointsLedgerUpsert {
	u.SetExcluded(pointsledger.FieldDelta)
	return u
}

// AddDelta adds v to the "delta" field.
func (u *PointsLedgerUpsert) AddDelta(v int64) *PointsLedgerUpsert {
	u.Add(pointsledger.FieldDelta, v)
	return u
}

// SetBalanceAfter sets the "balance_after" field.
func (u *PointsLedgerUpsert) SetBalanceAfter(v int64) *PointsLedgerUpsert {
	u.Set(pointsledger.FieldBalanceAfter, v)
	return u
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *PointsLedgerUpsert) UpdateBalanceAfter() *PointsLedgerUpsert {
	u.SetExcluded(pointsledger.FieldBalanceAfter)
	return u
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *PointsLedgerUpsert) AddBalanceAfter(v int64) *PointsLedgerUpsert {
	u.Add(pointsledger.FieldBalanceAfter, v)
	return u
}

// SetReason sets the "reason" field.
func (u *PointsLedgerUpsert) SetReason(v string) *PointsLedgerUpsert {
	u.Set(pointsledger.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PointsLedgerUpsert) UpdateReason() *PointsLedgerUpsert {
	u.SetExcluded(pointsledger.FieldReason)
	return u
}

// SetNote sets the "note" field.
func (u *PointsLedgerUpsert) SetNote(v string) *PointsLedgerUpsert {
	u.Set(pointsledger.FieldNote, v)
	return u
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *PointsLedgerUpsert) UpdateNote() *PointsLedgerUpsert {
	u.SetExcluded(pointsledger.FieldNote)
	return u
}

// ClearNote clears the value of the "note" field.
func (u *PointsLedgerUpsert) ClearNote() *PointsLedgerUpsert {
	u.SetNull(pointsledger.FieldNote)
	return u
}

// SetPaymentID sets the "payment_id" field.
func (u *PointsLedgerUpsert) SetPaymentID(v int) *PointsLedgerUpsert {
	u.Set(pointsledger.FieldPaymentID, v)
	return u
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *PointsLedgerUpsert) UpdatePaymentID() *PointsLedgerUpsert {
	u.SetExcluded(pointsledger.FieldPaymentID)
	return u
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *PointsLedgerUpsert) ClearPaymentID() *PointsLedgerUpsert {
	u.SetNull(pointsledger.FieldPaymentID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PointsLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PointsLedgerUpsertOne) UpdateNewValues() *PointsLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pointsledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PointsLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PointsLedgerUpsertOne) Ignore() *PointsLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PointsLedgerUpsertOne) DoNothing() *PointsLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PointsLedgerCreate.OnConflict
// documentation for more info.
func (u *PointsLedgerUpsertOne) Update(set func(*PointsLedgerUpsert)) *PointsLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PointsLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PointsLedgerUpsertOne) SetUpdatedAt(v time.Time) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PointsLedgerUpsertOne) UpdateUpdatedAt() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PointsLedgerUpsertOne) SetDeletedAt(v time.Time) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PointsLedgerUpsertOne) UpdateDeletedAt() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PointsLedgerUpsertOne) ClearDeletedAt() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PointsLedgerUpsertOne) SetUserID(v int) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PointsLedgerUpsertOne) UpdateUserID() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *PointsLedgerUpsertOne) ClearUserID() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.ClearUserID()
	})
}

// SetDelta sets the "delta" field.
func (u *PointsLedgerUpsertOne) SetDelta(v int64) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetDelta(v)
	})
}

// AddDelta adds v to the "delta" field.
func (u *PointsLedgerUpsertOne) AddDelta(v int64) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.AddDelta(v)
	})
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *PointsLedgerUpsertOne) UpdateDelta() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateDelta()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *PointsLedgerUpsertOne) SetBalanceAfter(v int64) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *PointsLedgerUpsertOne) AddBalanceAfter(v int64) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *PointsLedgerUpsertOne) UpdateBalanceAfter() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetReason sets the "reason" field.
func (u *PointsLedgerUpsertOne) SetReason(v string) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PointsLedgerUpsertOne) UpdateReason() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetNote sets the "note" field.
func (u *PointsLedgerUpsertOne) SetNote(v string) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *PointsLedgerUpsertOne) UpdateNote() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *PointsLedgerUpsertOne) ClearNote() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.ClearNote()
	})
}

// SetPaymentID sets the "payment_id" field.
func (u *PointsLedgerUpsertOne) SetPaymentID(v int) *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetPaymentID(v)
	})
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *PointsLedgerUpsertOne) UpdatePaymentID() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdatePaymentID()
	})
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *PointsLedgerUpsertOne) ClearPaymentID() *PointsLedgerUpsertOne {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.ClearPaymentID()
	})
}

// Exec executes the query.
func (u *PointsLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PointsLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PointsLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PointsLedgerUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PointsLedgerUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *PointsLedgerCreate) SetRawID(t int) *PointsLedgerCreate {
	m.mutation.SetRawID(t)
	return m
}

// PointsLedgerCreateBulk is the builder for creating many PointsLedger entities in bulk.
type PointsLedgerCreateBulk struct {
	config
	err      error
	builders []*PointsLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the PointsLedger entities in the database.
func (plcb *PointsLedgerCreateBulk) Save(ctx context.Context) ([]*PointsLedger, error) {
	if plcb.err != nil {
		return nil, plcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(plcb.builders))
	nodes := make([]*PointsLedger, len(plcb.builders))
	mutators := make([]Mutator, len(plcb.builders))
	for i := range plcb.builders {
		func(i int, root context.Context) {
			builder := plcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PointsLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, plcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = plcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, plcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, plcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (plcb *PointsLedgerCreateBulk) SaveX(ctx context.Context) []*PointsLedger {
	v, err := plcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (plcb *PointsLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := plcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plcb *PointsLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := plcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PointsLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PointsLedgerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (plcb *PointsLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *PointsLedgerUpsertBulk {
	plcb.conflict = opts
	return &PointsLedgerUpsertBulk{
		create: plcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PointsLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (plcb *PointsLedgerCreateBulk) OnConflictColumns(columns ...string) *PointsLedgerUpsertBulk {
	plcb.conflict = append(plcb.conflict, sql.ConflictColumns(columns...))
	return &PointsLedgerUpsertBulk{
		create: plcb,
	}
}

// PointsLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of PointsLedger nodes.
type PointsLedgerUpsertBulk struct {
	create *PointsLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PointsLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PointsLedgerUpsertBulk) UpdateNewValues() *PointsLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pointsledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PointsLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PointsLedgerUpsertBulk) Ignore() *PointsLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PointsLedgerUpsertBulk) DoNothing() *PointsLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PointsLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *PointsLedgerUpsertBulk) Update(set func(*PointsLedgerUpsert)) *PointsLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PointsLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PointsLedgerUpsertBulk) SetUpdatedAt(v time.Time) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PointsLedgerUpsertBulk) UpdateUpdatedAt() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PointsLedgerUpsertBulk) SetDeletedAt(v time.Time) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PointsLedgerUpsertBulk) UpdateDeletedAt() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PointsLedgerUpsertBulk) ClearDeletedAt() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *PointsLedgerUpsertBulk) SetUserID(v int) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PointsLedgerUpsertBulk) UpdateUserID() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *PointsLedgerUpsertBulk) ClearUserID() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.ClearUserID()
	})
}

// SetDelta sets the "delta" field.
func (u *PointsLedgerUpsertBulk) SetDelta(v int64) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetDelta(v)
	})
}

// AddDelta adds v to the "delta" field.
func (u *PointsLedgerUpsertBulk) AddDelta(v int64) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.AddDelta(v)
	})
}

// UpdateDelta sets the "delta" field to the value that was provided on create.
func (u *PointsLedgerUpsertBulk) UpdateDelta() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateDelta()
	})
}

// SetBalanceAfter sets the "balance_after" field.
func (u *PointsLedgerUpsertBulk) SetBalanceAfter(v int64) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetBalanceAfter(v)
	})
}

// AddBalanceAfter adds v to the "balance_after" field.
func (u *PointsLedgerUpsertBulk) AddBalanceAfter(v int64) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.AddBalanceAfter(v)
	})
}

// UpdateBalanceAfter sets the "balance_after" field to the value that was provided on create.
func (u *PointsLedgerUpsertBulk) UpdateBalanceAfter() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateBalanceAfter()
	})
}

// SetReason sets the "reason" field.
func (u *PointsLedgerUpsertBulk) SetReason(v string) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PointsLedgerUpsertBulk) UpdateReason() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetNote sets the "note" field.
func (u *PointsLedgerUpsertBulk) SetNote(v string) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetNote(v)
	})
}

// UpdateNote sets the "note" field to the value that was provided on create.
func (u *PointsLedgerUpsertBulk) UpdateNote() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdateNote()
	})
}

// ClearNote clears the value of the "note" field.
func (u *PointsLedgerUpsertBulk) ClearNote() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.ClearNote()
	})
}

// SetPaymentID sets the "payment_id" field.
func (u *PointsLedgerUpsertBulk) SetPaymentID(v int) *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.SetPaymentID(v)
	})
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *PointsLedgerUpsertBulk) UpdatePaymentID() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.UpdatePaymentID()
	})
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *PointsLedgerUpsertBulk) ClearPaymentID() *PointsLedgerUpsertBulk {
	return u.Update(func(s *PointsLedgerUpsert) {
		s.ClearPaymentID()
	})
}

// Exec executes the query.
func (u *PointsLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PointsLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PointsLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PointsLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
