// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/pointsledger"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// PointsLedgerDelete is the builder for deleting a PointsLedger entity.
type PointsLedgerDelete struct {
	config
	hooks    []Hook
	mutation *PointsLedgerMutation
}

// Where appends a list predicates to the PointsLedgerDelete builder.
func (pld *PointsLedgerDelete) Where(ps ...predicate.PointsLedger) *PointsLedgerDelete {
	pld.mutation.Where(ps...)
	return pld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pld *PointsLedgerDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pld.sqlExec, pld.mutation, pld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pld *PointsLedgerDelete) ExecX(ctx context.Context) int {
	n, err := pld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pld *PointsLedgerDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pointsledger.Table, sqlgraph.NewFieldSpec(pointsledger.FieldID, field.TypeInt))
	if ps := pld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pld.mutation.done = true
	return affected, err
}

// PointsLedgerDeleteOne is the builder for deleting a single PointsLedger entity.
type PointsLedgerDeleteOne struct {
	pld *PointsLedgerDelete
}

// Where appends a list predicates to the PointsLedgerDelete builder.
func (pldo *PointsLedgerDeleteOne) Where(ps ...predicate.PointsLedger) *PointsLedgerDeleteOne {
	pldo.pld.mutation.Where(ps...)
	return pldo
}

// Exec executes the deletion query.
func (pldo *PointsLedgerDeleteOne) Exec(ctx context.Context) error {
	n, err := pldo.pld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pointsledger.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pldo *PointsLedgerDeleteOne) ExecX(ctx context.Context) {
	if err := pldo.Exec(ctx); err != nil {
		panic(err)
	}
}
