// Code generated by ent, DO NOT EDIT.

package giftcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldDeletedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCode, v))
}

// ProductType applies equality check predicate on the "product_type" field. It's identical to ProductTypeEQ.
func ProductType(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldProductType, v))
}

// Num applies equality check predicate on the "num" field. It's identical to NumEQ.
func Num(v int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldNum, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldName, v))
}

// Used applies equality check predicate on the "used" field. It's identical to UsedEQ.
func Used(v bool) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsed, v))
}

// UsedBy applies equality check predicate on the "used_by" field. It's identical to UsedByEQ.
func UsedBy(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsedBy, v))
}

// UsedByEmail applies equality check predicate on the "used_by_email" field. It's identical to UsedByEmailEQ.
func UsedByEmail(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsedByEmail, v))
}

// CreatedByEmail applies equality check predicate on the "created_by_email" field. It's identical to CreatedByEmailEQ.
func CreatedByEmail(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCreatedByEmail, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldDeletedAt))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContainsFold(FieldCode, v))
}

// ProductTypeEQ applies the EQ predicate on the "product_type" field.
func ProductTypeEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldProductType, v))
}

// ProductTypeNEQ applies the NEQ predicate on the "product_type" field.
func ProductTypeNEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldProductType, v))
}

// ProductTypeIn applies the In predicate on the "product_type" field.
func ProductTypeIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldProductType, vs...))
}

// ProductTypeNotIn applies the NotIn predicate on the "product_type" field.
func ProductTypeNotIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldProductType, vs...))
}

// ProductTypeGT applies the GT predicate on the "product_type" field.
func ProductTypeGT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldProductType, v))
}

// ProductTypeGTE applies the GTE predicate on the "product_type" field.
func ProductTypeGTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldProductType, v))
}

// ProductTypeLT applies the LT predicate on the "product_type" field.
func ProductTypeLT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldProductType, v))
}

// ProductTypeLTE applies the LTE predicate on the "product_type" field.
func ProductTypeLTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldProductType, v))
}

// ProductTypeContains applies the Contains predicate on the "product_type" field.
func ProductTypeContains(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContains(FieldProductType, v))
}

// ProductTypeHasPrefix applies the HasPrefix predicate on the "product_type" field.
func ProductTypeHasPrefix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasPrefix(FieldProductType, v))
}

// ProductTypeHasSuffix applies the HasSuffix predicate on the "product_type" field.
func ProductTypeHasSuffix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasSuffix(FieldProductType, v))
}

// ProductTypeEqualFold applies the EqualFold predicate on the "product_type" field.
func ProductTypeEqualFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEqualFold(FieldProductType, v))
}

// ProductTypeContainsFold applies the ContainsFold predicate on the "product_type" field.
func ProductTypeContainsFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContainsFold(FieldProductType, v))
}

// NumEQ applies the EQ predicate on the "num" field.
func NumEQ(v int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldNum, v))
}

// NumNEQ applies the NEQ predicate on the "num" field.
func NumNEQ(v int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldNum, v))
}

// NumIn applies the In predicate on the "num" field.
func NumIn(vs ...int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldNum, vs...))
}

// NumNotIn applies the NotIn predicate on the "num" field.
func NumNotIn(vs ...int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldNum, vs...))
}

// NumGT applies the GT predicate on the "num" field.
func NumGT(v int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldNum, v))
}

// NumGTE applies the GTE predicate on the "num" field.
func NumGTE(v int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldNum, v))
}

// NumLT applies the LT predicate on the "num" field.
func NumLT(v int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldNum, v))
}

// NumLTE applies the LTE predicate on the "num" field.
func NumLTE(v int64) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldNum, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContainsFold(FieldName, v))
}

// UsedEQ applies the EQ predicate on the "used" field.
func UsedEQ(v bool) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsed, v))
}

// UsedNEQ applies the NEQ predicate on the "used" field.
func UsedNEQ(v bool) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldUsed, v))
}

// UsedByEQ applies the EQ predicate on the "used_by" field.
func UsedByEQ(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsedBy, v))
}

// UsedByNEQ applies the NEQ predicate on the "used_by" field.
func UsedByNEQ(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldUsedBy, v))
}

// UsedByIn applies the In predicate on the "used_by" field.
func UsedByIn(vs ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldUsedBy, vs...))
}

// UsedByNotIn applies the NotIn predicate on the "used_by" field.
func UsedByNotIn(vs ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldUsedBy, vs...))
}

// UsedByIsNil applies the IsNil predicate on the "used_by" field.
func UsedByIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldUsedBy))
}

// UsedByNotNil applies the NotNil predicate on the "used_by" field.
func UsedByNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldUsedBy))
}

// UsedByEmailEQ applies the EQ predicate on the "used_by_email" field.
func UsedByEmailEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsedByEmail, v))
}

// UsedByEmailNEQ applies the NEQ predicate on the "used_by_email" field.
func UsedByEmailNEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldUsedByEmail, v))
}

// UsedByEmailIn applies the In predicate on the "used_by_email" field.
func UsedByEmailIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldUsedByEmail, vs...))
}

// UsedByEmailNotIn applies the NotIn predicate on the "used_by_email" field.
func UsedByEmailNotIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldUsedByEmail, vs...))
}

// UsedByEmailGT applies the GT predicate on the "used_by_email" field.
func UsedByEmailGT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldUsedByEmail, v))
}

// UsedByEmailGTE applies the GTE predicate on the "used_by_email" field.
func UsedByEmailGTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldUsedByEmail, v))
}

// UsedByEmailLT applies the LT predicate on the "used_by_email" field.
func UsedByEmailLT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldUsedByEmail, v))
}

// UsedByEmailLTE applies the LTE predicate on the "used_by_email" field.
func UsedByEmailLTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldUsedByEmail, v))
}

// UsedByEmailContains applies the Contains predicate on the "used_by_email" field.
func UsedByEmailContains(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContains(FieldUsedByEmail, v))
}

// UsedByEmailHasPrefix applies the HasPrefix predicate on the "used_by_email" field.
func UsedByEmailHasPrefix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasPrefix(FieldUsedByEmail, v))
}

// UsedByEmailHasSuffix applies the HasSuffix predicate on the "used_by_email" field.
func UsedByEmailHasSuffix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasSuffix(FieldUsedByEmail, v))
}

// UsedByEmailIsNil applies the IsNil predicate on the "used_by_email" field.
func UsedByEmailIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldUsedByEmail))
}

// UsedByEmailNotNil applies the NotNil predicate on the "used_by_email" field.
func UsedByEmailNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldUsedByEmail))
}

// UsedByEmailEqualFold applies the EqualFold predicate on the "used_by_email" field.
func UsedByEmailEqualFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEqualFold(FieldUsedByEmail, v))
}

// UsedByEmailContainsFold applies the ContainsFold predicate on the "used_by_email" field.
func UsedByEmailContainsFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContainsFold(FieldUsedByEmail, v))
}

// CreatedByEmailEQ applies the EQ predicate on the "created_by_email" field.
func CreatedByEmailEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCreatedByEmail, v))
}

// CreatedByEmailNEQ applies the NEQ predicate on the "created_by_email" field.
func CreatedByEmailNEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldCreatedByEmail, v))
}

// CreatedByEmailIn applies the In predicate on the "created_by_email" field.
func CreatedByEmailIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldCreatedByEmail, vs...))
}

// CreatedByEmailNotIn applies the NotIn predicate on the "created_by_email" field.
func CreatedByEmailNotIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldCreatedByEmail, vs...))
}

// CreatedByEmailGT applies the GT predicate on the "created_by_email" field.
func CreatedByEmailGT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldCreatedByEmail, v))
}

// CreatedByEmailGTE applies the GTE predicate on the "created_by_email" field.
func CreatedByEmailGTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldCreatedByEmail, v))
}

// CreatedByEmailLT applies the LT predicate on the "created_by_email" field.
func CreatedByEmailLT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldCreatedByEmail, v))
}

// CreatedByEmailLTE applies the LTE predicate on the "created_by_email" field.
func CreatedByEmailLTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldCreatedByEmail, v))
}

// CreatedByEmailContains applies the Contains predicate on the "created_by_email" field.
func CreatedByEmailContains(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContains(FieldCreatedByEmail, v))
}

// CreatedByEmailHasPrefix applies the HasPrefix predicate on the "created_by_email" field.
func CreatedByEmailHasPrefix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasPrefix(FieldCreatedByEmail, v))
}

// CreatedByEmailHasSuffix applies the HasSuffix predicate on the "created_by_email" field.
func CreatedByEmailHasSuffix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasSuffix(FieldCreatedByEmail, v))
}

// CreatedByEmailIsNil applies the IsNil predicate on the "created_by_email" field.
func CreatedByEmailIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldCreatedByEmail))
}

// CreatedByEmailNotNil applies the NotNil predicate on the "created_by_email" field.
func CreatedByEmailNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldCreatedByEmail))
}

// CreatedByEmailEqualFold applies the EqualFold predicate on the "created_by_email" field.
func CreatedByEmailEqualFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEqualFold(FieldCreatedByEmail, v))
}

// CreatedByEmailContainsFold applies the ContainsFold predicate on the "created_by_email" field.
func CreatedByEmailContainsFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContainsFold(FieldCreatedByEmail, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.GiftCode {
	return predicate.GiftCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.GiftCode {
	return predicate.GiftCode(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GiftCode) predicate.GiftCode {
	return predicate.GiftCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GiftCode) predicate.GiftCode {
	return predicate.GiftCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GiftCode) predicate.GiftCode {
	return predicate.GiftCode(sql.NotPredicates(p))
}
