// Code generated by ent, DO NOT EDIT.

package abusereport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldDeletedAt, v))
}

// ShareID applies equality check predicate on the "share_id" field. It's identical to ShareIDEQ.
func ShareID(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldShareID, v))
}

// ShareURL applies equality check predicate on the "share_url" field. It's identical to ShareURLEQ.
func ShareURL(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldShareURL, v))
}

// ReporterEmail applies equality check predicate on the "reporter_email" field. It's identical to ReporterEmailEQ.
func ReporterEmail(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReporterEmail, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldIP, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReason, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldStatus, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldDeletedAt))
}

// ShareIDEQ applies the EQ predicate on the "share_id" field.
func ShareIDEQ(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldShareID, v))
}

// ShareIDNEQ applies the NEQ predicate on the "share_id" field.
func ShareIDNEQ(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldShareID, v))
}

// ShareIDIn applies the In predicate on the "share_id" field.
func ShareIDIn(vs ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldShareID, vs...))
}

// ShareIDNotIn applies the NotIn predicate on the "share_id" field.
func ShareIDNotIn(vs ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldShareID, vs...))
}

// ShareIDGT applies the GT predicate on the "share_id" field.
func ShareIDGT(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldShareID, v))
}

// ShareIDGTE applies the GTE predicate on the "share_id" field.
func ShareIDGTE(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldShareID, v))
}

// ShareIDLT applies the LT predicate on the "share_id" field.
func ShareIDLT(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldShareID, v))
}

// ShareIDLTE applies the LTE predicate on the "share_id" field.
func ShareIDLTE(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldShareID, v))
}

// ShareIDIsNil applies the IsNil predicate on the "share_id" field.
func ShareIDIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldShareID))
}

// ShareIDNotNil applies the NotNil predicate on the "share_id" field.
func ShareIDNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldShareID))
}

// ShareURLEQ applies the EQ predicate on the "share_url" field.
func ShareURLEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldShareURL, v))
}

// ShareURLNEQ applies the NEQ predicate on the "share_url" field.
func ShareURLNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldShareURL, v))
}

// ShareURLIn applies the In predicate on the "share_url" field.
func ShareURLIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldShareURL, vs...))
}

// ShareURLNotIn applies the NotIn predicate on the "share_url" field.
func ShareURLNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldShareURL, vs...))
}

// ShareURLGT applies the GT predicate on the "share_url" field.
func ShareURLGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldShareURL, v))
}

// ShareURLGTE applies the GTE predicate on the "share_url" field.
func ShareURLGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldShareURL, v))
}

// ShareURLLT applies the LT predicate on the "share_url" field.
func ShareURLLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldShareURL, v))
}

// ShareURLLTE applies the LTE predicate on the "share_url" field.
func ShareURLLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldShareURL, v))
}

// ShareURLContains applies the Contains predicate on the "share_url" field.
func ShareURLContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldShareURL, v))
}

// ShareURLHasPrefix applies the HasPrefix predicate on the "share_url" field.
func ShareURLHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldShareURL, v))
}

// ShareURLHasSuffix applies the HasSuffix predicate on the "share_url" field.
func ShareURLHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldShareURL, v))
}

// ShareURLIsNil applies the IsNil predicate on the "share_url" field.
func ShareURLIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldShareURL))
}

// ShareURLNotNil applies the NotNil predicate on the "share_url" field.
func ShareURLNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldShareURL))
}

// ShareURLEqualFold applies the EqualFold predicate on the "share_url" field.
func ShareURLEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldShareURL, v))
}

// ShareURLContainsFold applies the ContainsFold predicate on the "share_url" field.
func ShareURLContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldShareURL, v))
}

// ReporterEmailEQ applies the EQ predicate on the "reporter_email" field.
func ReporterEmailEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReporterEmail, v))
}

// ReporterEmailNEQ applies the NEQ predicate on the "reporter_email" field.
func ReporterEmailNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldReporterEmail, v))
}

// ReporterEmailIn applies the In predicate on the "reporter_email" field.
func ReporterEmailIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldReporterEmail, vs...))
}

// ReporterEmailNotIn applies the NotIn predicate on the "reporter_email" field.
func ReporterEmailNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldReporterEmail, vs...))
}

// ReporterEmailGT applies the GT predicate on the "reporter_email" field.
func ReporterEmailGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldReporterEmail, v))
}

// ReporterEmailGTE applies the GTE predicate on the "reporter_email" field.
func ReporterEmailGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldReporterEmail, v))
}

// ReporterEmailLT applies the LT predicate on the "reporter_email" field.
func ReporterEmailLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldReporterEmail, v))
}

// ReporterEmailLTE applies the LTE predicate on the "reporter_email" field.
func ReporterEmailLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldReporterEmail, v))
}

// ReporterEmailContains applies the Contains predicate on the "reporter_email" field.
func ReporterEmailContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldReporterEmail, v))
}

// ReporterEmailHasPrefix applies the HasPrefix predicate on the "reporter_email" field.
func ReporterEmailHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldReporterEmail, v))
}

// ReporterEmailHasSuffix applies the HasSuffix predicate on the "reporter_email" field.
func ReporterEmailHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldReporterEmail, v))
}

// ReporterEmailIsNil applies the IsNil predicate on the "reporter_email" field.
func ReporterEmailIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldReporterEmail))
}

// ReporterEmailNotNil applies the NotNil predicate on the "reporter_email" field.
func ReporterEmailNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldReporterEmail))
}

// ReporterEmailEqualFold applies the EqualFold predicate on the "reporter_email" field.
func ReporterEmailEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldReporterEmail, v))
}

// ReporterEmailContainsFold applies the ContainsFold predicate on the "reporter_email" field.
func ReporterEmailContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldReporterEmail, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldIP, v))
}

// IPIsNil applies the IsNil predicate on the "ip" field.
func IPIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldIP))
}

// IPNotNil applies the NotNil predicate on the "ip" field.
func IPNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldIP))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldIP, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldStatus, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldNote, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AbuseReport) predicate.AbuseReport {
	return predicate.AbuseReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AbuseReport) predicate.AbuseReport {
	return predicate.AbuseReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AbuseReport) predicate.AbuseReport {
	return predicate.AbuseReport(sql.NotPredicates(p))
}
